cds/demosite/data/cds-photos.xml, cds/demosite/manage.py
* Indroduces `inveniomanage demosite photos` command
* NOTE: It populates only photo records
=> demosite: add multimedia photo demo data

MANIFEST.in, cds/base/output_formats/HD.bfo, cds/base/templates/format/record/multimedia/layout.tpl, cds/base/templates/format/record/multimedia/pictures/base.tpl, cds/base/templates/format/record/multimedia/pictures/photolab.tpl, cds/base/templates/format/record/multimedia/videos/base.tpl, cds/base/templates/format/record/multimedia/videos/rush.tpl, cds/base/templates/records/helpers/multimedia.html, cds/base/templates/records/helpers/record.html, cds/base/templates/search/collection.html
* Migrates `photolab` bibformat to `jinja`.
* Adds macros for each entity `record`, `multimedia` etc.
* Adds `list`, `label`, `separated` views.
* Adds template function `wrap_with_link`.
* NOTE: It's just a proof of concept.
=> base: bibformat migration

Dockerfile, cds/modules/records/__init__.py, cds/modules/records/data/__init__.py, docker-compose.yml, docker/docker-entrypoint.sh, requirements.txt
* Changes base image to python:3.5-slim
* Adds libpq-dev for postgres support and libjpeg-dev needed by pillow.
* Combines RUN statements to reduce the image size.
* Adds a docker-entrypoint.
* Fixes the missing python egg folder if the local repository is fresh cloned
and mounted as volume.
Signed-off-by: David Zerulla <ddaze@outlook.de>
=> docker: improves image size and build speed with better caching.

cds/modules/theme/static/scss/cds.scss
* Aligns thumbnails in results to the right edge of the screen.
=> search-ui: fix result thumbnail alignment

cds/config.py, cds/modules/access/__init__.py, cds/modules/access/access_control.py, cds/modules/fixtures/cli.py, cds/modules/records/mappings/records/default-v1.0.0.json, tests/unit/test_access.py
* NEW Enables access control on records, based on CERN groups a 
use belongs to. This information is provided by the CERN OAuth server.
* NEW Enables access control on files, by inheriting them from the 
record that is linked to the bucket they reside in.
* Updated the ElasticSearch `default-record-v1.0.0` mapping to include 
the `_access` field.
* FIX Fixes issue with improper insertion of test files by the 
`cds fixtures files` CLI command.
* Increases test coverage.
=> access: record and file permissions

cds/config.py, cds/modules/cds_iiif/utils.py, cds/modules/records/minters.py, cds/modules/records/providers.py, setup.py, tests/unit/test_provider.py
* Adds the minter cds_recid that retrieves new recids from a given
endpoint.  (#161)
=> records: addition of CDS recid provider

cds/modules/deposit/api.py, cds/modules/deposit/static/json/cds_deposit/form.json, cds/modules/migrator/records.py, cds/modules/records/minters.py, cds/modules/records/providers.py, tests/unit/test_deposit.py, tests/unit/test_provider.py
* Removes is_published and _process_files from CDSDeposit as they are
not needed.
* Updates schema form for deposit and the corresponding mappings.
* Changes the provider, so in the DEBUG mode, it doesn't contact the
RECORDS_ID_PROVIDER_ENDPOINT but generates the pid localy.
* Bumps deposit version.
=> deposit: fixes for publishing deposits

cds/modules/access/access_control.py
This fixes the
`TypeError: unorderable types: int() < str()`
error that pops up in the console.
=> access: fix TypeError in access_control

cds/modules/webhooks/receivers.py, cds/modules/webhooks/task_classes.py, cds/modules/webhooks/tasks.py, cds/modules/webhooks/views.py, setup.py, tests/unit/conftest.py, tests/unit/test_webhook_helpers.py, tests/unit/test_webhook_receivers.py, tests/unit/test_webhook_tasks.py
webhooks: high-level tests
* Adds high-level tests (i.e. tests that immediately do `POST` requests
on the receivers) in addition to the atomic Celery task tests.
(closes #284)
* Minor code refactoring and cleaning on Webhook tasks and receivers.
* Fixes webhook tests. (closes #294)
=> Receiver tests

cds/config.py, cds/modules/webhooks/tasks.py
* Adds pickle to ``CELERY_ACCEPT_CONTENT`` as chain and group are not
JSON serializable.
* Casts record UUID to string when scheduling ``update_record`` task.
=> webhook: pickle as accept content

cds/modules/webhooks/tasks.py, tests/unit/test_deposit.py, tests/unit/test_webhook_receivers.py, tests/unit/test_webhook_tasks.py
* When calling ``set_contents`` using a ``BytesIO`` object wrapping
``response.content`` causes the full response to be downloaded and
stored in memory. Using ``response.raw`` instead solves the issue.
* Adds ``size`` parameter to the ``set_stream``.
=> webhooks: file streaming fix

Dockerfile, INSTALL.rst, docker-compose.yml, docker/es/Dockerfile
* Fixes Docker-based installation procedures by (i) including necessary
prerequisites (imagemagick), (ii) updating runtime instructions for Flask
0.11, (iii) installing appropriate npm package versions. (iv) installing
Elasticsearch mapper-attachments plugin.
* This makes the site installable via Docker, although further improvements are
necessary, e.g. regarding fixtures and `imprint._complete_date`.
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>
=> docker: fix installation procedures

cds/modules/webhooks/tasks.py
* Fixes issue with ObjectVersionTag creation in `video_extract_frames`.
=> webhooks: tag creation fix

cds/modules/webhooks/tasks.py, tests/unit/test_webhook_tasks.py
=> webhooks: fix celery retry on update_record

cds/modules/webhooks/receivers.py, cds/modules/webhooks/tasks.py, tests/unit/test_webhook_tasks.py
* Changes execution of the video transcoding to spawn multiple Celery
tasks instead of one (i.e. one task for each video preset).
=> webhooks: multiple transcoding tasks

cds/modules/webhooks/receivers.py, tests/unit/test_webhook_receivers.py, tests/unit/test_webhook_status.py, tests/unit/test_webhook_views.py
* Removes event deletion on receiver delete.
* Adds a test to restart the AVC workflow.
=> webhooks: event deletion removal

cds/modules/ffmpeg/__init__.py, cds/modules/ffmpeg/ffmpeg.py, tests/unit/test_ffmpeg.py, tests/unit/test_webhook_tasks.py
* Calculates aspect ratio from a video's dimensions, in case it is
missing from its metadata information. (closes #351)
* Adds tests for coverage.
=> ffmpeg: automatic calculation of aspect ratio

cds/config.py
* Adds pid converter to RECORDS_REST_ENDPOINTS in order for pass_record
to work properly.
=> api: add converter to records REST endpoints

scripts/setup-npm.sh
* Sets a pin to the clean-css version installed because of some
incompatibility. (closes #390)
=> installation: pin clean-css version to 3.4.24

cds/modules/deposit/api.py, tests/unit/test_deposit.py
* Sorts deposit files by length first, so that e.g. 10 comes after 1.
* Prevents deposits from having duplicate files due to bucket snapshots.
=> deposit: deposit file fixes

cds/modules/deposit/static/templates/cds_deposit/types/common/uploader.html, cds/modules/theme/static/scss/cds.scss
* Changes each row of extracted frames to contain five thumbnails.
(fixes #437)
=> deposit: five frames per row

cds/modules/previewer/templates/cds_previewer/previewer_video.html
* Show preview image of embedded videos in deposits. (closes #439)
=> deposit: embedded video preview

cds/modules/deposit/bundles.py, cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js, cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js, cds/modules/deposit/static/js/cds_deposit/avc/providers/errorRepresentations.js, cds/modules/deposit/static/templates/cds_deposit/types/video/form.html
* Maps errors sent by the AV workflow to human readable ones.
(closes #445)
=> deposit: human readable errors

cds/modules/deposit/bundles.py, cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js, cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js, cds/modules/deposit/static/js/cds_deposit/avc/filters/orderTasks.js, cds/modules/deposit/static/js/cds_deposit/avc/providers/taskRepresentations.js, cds/modules/deposit/static/templates/cds_deposit/deposits.html, cds/modules/deposit/static/templates/cds_deposit/search/results.html, cds/modules/deposit/static/templates/cds_deposit/types/video/form.html, cds/modules/deposit/templates/cds_deposit/index.html, cds/modules/theme/bundles.py, cds/modules/theme/static/js/main.js, setup.py
* Displays the status of the workflow tasks in the deposit list for each
deposit. (closes #464)
* Moves the Angular deposit module that contains filters, providers,
components and factories to a different file.
* Changes the errorRepresentations provider to the more generic
taskRepresentations.
=> deposit: task status in deposit list

tests/unit/conftest.py
Removes the `depid` fixture - it doesn't seem to be used anywhere (tests use the `cds_depid` instead) and simply trying to use this fixture in a test, gives an error:
```
def do_execute(self, cursor, statement, parameters, context=None):
>       cursor.execute(statement, parameters)
E       psycopg2.IntegrityError: duplicate key value violates unique constraint "pk_sequencegenerator_template"
E       DETAIL:  Key (name)=(project-v1_0_0) already exists.
../../.virtualenvs/cdslabs3p3/lib/python3.5/site-packages/sqlalchemy/engine/default.py:470: IntegrityError
```
=> tests: remove unused depid fixture

cds/modules/webhooks/tasks.py, tests/unit/test_webhook_tasks.py
* Avoids to raise a resolution exception on transcoding task.
(closes #477)
=> webhooks: avoid raise in resolution not found

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js, cds/modules/deposit/static/templates/cds_deposit/deposits.html
* Displays a "Permission denied" message if a user tries to access a
deposit without having permission to. (closes #474)
=> deposit: permission denied message

cds/modules/deposit/mappings/deposits/records/project-v1.0.0.json, cds/modules/deposit/mappings/deposits/records/video-v1.0.0.json
* Adds `license` to deposit mappings. (closes #497)
=> mappings: addition of license

cds/modules/deposit/api.py, cds/modules/webhooks/receivers.py, cds/modules/webhooks/tasks.py, tests/unit/helpers.py, tests/unit/test_webhook_receivers.py, tests/unit/test_webhook_views.py
* A file dump now contains information regarding its `media`, `content`
and `context` type. (closes #431)
=> deposit: dump file's type information

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js, cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js
* Fetch transcoding presets from AVC workflow response.
=> deposit: dynamic transcoding presets

cds/config.py, cds/modules/deposit/api.py, cds/modules/ffmpeg/ffmpeg.py, cds/modules/fixtures/cli.py, cds/modules/previewer/api.py, cds/modules/previewer/extensions/video.py, cds/modules/records/serializers/smil.py, cds/modules/records/serializers/vtt.py, cds/modules/records/views.py, cds/modules/webhooks/tasks.py, setup.py, tests/unit/conftest.py, tests/unit/helpers.py, tests/unit/test_deposit.py, tests/unit/test_ffmpeg.py, tests/unit/test_fixtures.py, tests/unit/test_previewer.py, tests/unit/test_records.py, tests/unit/test_serializer.py, tests/unit/test_video.py, tests/unit/test_webhook_tasks.py
* Configured THEO player to display thumbnails on hover. (closes #415)
* Separate endpoint for exporting VTT file. ()
* Thumbnails provided as resized frames by IIIF.
* FFmpeg frame extraction now takes absolute time values instead of
percentages.
* Added `timestamp` tag on frame files.
* Registered CDSIIIF extension on `invenio_apps` too.
* Adds tests for coverage.
=> previewer: THEO-VTT integration

cds/modules/deposit/api.py, cds/modules/webhooks/receivers.py, cds/modules/webhooks/tasks.py, tests/unit/test_webhook_receivers.py, tests/unit/test_webhook_views.py
* Receivers now automatically extract `bucket_id` from given
deposit_id. (closes #411)
* Test refactoring.
=> webhooks: obsolete bucket_id parameter

cds/modules/deposit/search.py, cds/modules/records/permissions.py, cds/modules/records/search.py, tests/unit/conftest.py, tests/unit/test_access_search.py, tests/unit/test_project.py
* Drops usage of `_deposit.owners` in favor of `_access.update` for
deposit keeping all access rights definitions in the same key.
`_deposit.created+by` is still used. (addresses #518)
=> access: same access rights for deposit and record

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
* Video file extensions can be passed as an attribute to the
cds-deposits tag.
* Extensions are now case-insensitive. (references #594)
=> deposit: custom video file extensions

cds/modules/deposit/search.py, cds/modules/records/search.py, tests/unit/test_access_search.py
* If the `_access` key is missing in deposit it shouldn't make it
available to everyone, instead it should available only to its
creator.
* Users with the superadmin role don't send any filter to ES.
=> access: fix deposit ES filter

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js, cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js
* Allow saving of project metadata while processing video files.
(fixes #542)
* Fix javascript console error introduced by #590.
=> deposit: save during AVC workflow

cds/config.py, cds/modules/deposit/bundles.py, cds/modules/deposit/loaders/__init__.py, cds/modules/deposit/loaders/loader.py, cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js, cds/modules/deposit/static/js/cds_deposit/avc/components/cdsActions.js, cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js, cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js, cds/modules/deposit/static/js/cds_deposit/avc/factories/states.js, cds/modules/deposit/static/js/cds_deposit/avc/providers/depositActions.js, cds/modules/deposit/static/json/cds_deposit/forms/project.json, cds/modules/deposit/static/json/cds_deposit/forms/video.json, cds/modules/deposit/static/templates/cds_deposit/types/project/actions.html, cds/modules/deposit/static/templates/cds_deposit/types/video/actions.html, cds/modules/records/serializers/schemas/project.py, tests/unit/conftest.py, tests/unit/test_deposit.py, tests/unit/test_project_rest.py, tests/unit/test_video_rest.py
deposit: partial marshmallow loaders
* Adds partial marshmallow loaders, which are used when a specific
mimetype is present. (closes #324, closes #436)
* Adds payload sanitization on the front-end (i.e. removes empty
values in objects/arrays before sending payload).
* Removes required fields from Schema Form.
* Tests will be added on later PR (with data model updates).
Co-Authored-By: Nikos Filippakis <nikolaos.filippakis@cern.ch>
=> deposit: partial marshmallow loaders

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
* Fixes issue with non-video files not being attached to the project,\
when they are provided on the first uploader. (closes #593)
=> deposit: non-video file upload

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js, cds/modules/deposit/static/js/cds_deposit/avc/factories/states.js, cds/modules/deposit/static/js/cds_deposit/avc/providers/depositActions.js
* Adds the proper mimetype to the `Accept-Type` header, in addition to
`Content-Type`. (closes #607)
=> deposit: request headers for partial-validation

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js, cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js, cds/modules/deposit/static/templates/cds_deposit/deposits.html, cds/modules/deposit/static/templates/cds_deposit/types/project/actions.html, cds/modules/deposit/static/templates/cds_deposit/types/project/form.html, cds/modules/deposit/static/templates/cds_deposit/types/video/actions.html, cds/modules/deposit/static/templates/cds_deposit/types/video/form.html
* Cleans up handling of a deposit's schema form status. (#closes #486)
* NOTE Every individual form should use a different form model
(i.e. different indices in the `depositFormModels` array)
Co-Authored-By: Nikos Filippakis <nikolaos.filippakis@cern.ch>
=> deposit: proper schema form statuses

cds/config.py, cds/modules/deposit/templates/cds_deposit/index.html
* Changes the elasticsearch index used for deposit sorting. (closes #548)
* Selects a default "sort by" option if one isn't selected.
=> deposit: correct sort index

cds/modules/redirector/views.py, tests/unit/test_previewer.py
* Uses `recid_embed_default` instead of `recid_embed`.
=> redirector: embed link fix

cds/modules/fixtures/cli.py, cds/modules/fixtures/data/categories.json, tests/unit/test_fixtures.py
* Uses 3 digits for the counters in the sequence generator templates
and upper case for the category types. (closes #666)
=> fixtures: fix report number generation

cds/modules/deposit/bundles.py, cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js, cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js, cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js, cds/modules/deposit/static/json/cds_deposit/forms/video.json, cds/modules/deposit/static/templates/cds_deposit/types/video/form.html, cds/modules/webhooks/tasks.py
* Sets a video's title to its basename (i.e. filename without extension)
on upload, in order for the user to be able to identify individual
uploads. (closes #561)
* On completion of the `ExtractMetadataTask`, a video's default title
can get overwritten by the one inside the extracted metadata, if it
exists. (closes #425)
* Adds local storage for keeping track of video basenames and extracted
metadata.
* Fixes issue with prefilled `copyright.year` being an integer, instead
of a string.
* Adds `mov` to the default video extensions.
* Adds `extracted_metadata` inside the payload of the `on_success` SSE of
the `ExtractMetadataTask`, in order to prefill desired information
immediately without having to wait for an `update_deposit` SSE.
=> deposit: autocompletion from extracted metadata

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js, cds/modules/deposit/static/json/cds_deposit/forms/project.json, cds/modules/deposit/static/json/cds_deposit/forms/video.json, cds/modules/deposit/static/templates/cds_deposit/types/common/custom_authors_dialog.html, cds/modules/records/serializers/schemas/common.py, tests/unit/test_video_rest.py
* Allows adding custom keywords in deposit form field. (closes #683)
* Allows adding custom authors in deposit form field, in the form
`<FirstName>, <LastName>: <Affiliation>`. (closes #682)
* Removes schema description from authors' field. (closes #730)
=> deposit: custom keywords and authors

cds/modules/deposit/api.py, cds/modules/fixtures/cli.py, cds/modules/fixtures/video_utils.py, tests/unit/test_video.py, tests/unit/test_webhook_receivers.py
* Adds a function to create extra tags on video publish. (closes #727)
=> deposit: create extra tags on video publish

cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js, cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js, cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js, cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js, cds/modules/deposit/static/templates/cds_deposit/list.html, cds/modules/deposit/static/templates/cds_deposit/types/common/uploader.html
* Remove all SSE events except update_deposit and replace them with
feedback calls.
* Add deposit JS optimizations.
=> deposit: SSE events refactor

cds/config.py, cds/modules/records/providers.py
* Refactors the usage of the configuration variable responsible of setting the provider endpoint to ease deployments.
The config variable is now set in the puppet profile.
=> records: refactor recid provider

cds/config.py, cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js, cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js, cds/modules/deposit/static/json/cds_deposit/forms/project.json, cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/strapselect.html
* Fixes issue with access rights' field being empty by default.
* Makes the dependency `Type` has on `Category` more apparent to the
user. (closes #759)
* Fixes issues with confusing initial suggestions on `multiselect`
fields. (closes #741)
* Improves experience of `Author` autocompletion (e.g. stripping commas).
* `Keyword` autocompletion is now case-insensitive.
Signed-off-by: Orestis Melkonian melkon.or@gmail.com
=> deposit: UI fixes and improvements

cds/config.py, cds/modules/previewer/api.py, cds/modules/records/views.py, cds/modules/redirector/views.py, setup.py, tests/unit/test_records.py
* Adds a redirection endpoint for the legacy drupal export
(i.e. `/api/mediaexport?id=<rn>`). (closes #417)
* Enables serving serialized records immediately from the UI via
adding the `raw` query string in `record/<recid>/export/<format>?raw`.
=> redirector: drupal export legacy endpoint

cds/modules/deposit/static/templates/cds_deposit/types/project/form.html
* Replaces `Edit/Show less` with chevron arrows. (closes #805)
=> deposit: project form collapsing

cds/modules/deposit/static/json/cds_deposit/forms/project.json, cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/array.html
* By adding 'minLength' parameter to the 'options' of a json form, one
can specify when the 'Remove' button should be hidden for the arrays
of elements (for example in contributors, translations or access)
(closes #714).
=> deposit: array.html now accepts minLength parameter

cds/config.py, cds/modules/deposit/api.py, cds/modules/deposit/indexer.py, cds/modules/deposit/search.py, cds/modules/deposit/tasks.py, cds/modules/webhooks/status.py, tests/unit/test_deposit.py, tests/unit/test_webhook_receivers.py, tests/unit/test_webhook_status.py
* Saves permanently celery tasks status when required.
(closes #790) (closes #786)
=> deposit: permanent store celery tasks status

setup.py
* As the 0.14.2 version no longer has a bug that we were trying to
prevent by freezing the previous version
(inveniosoftware/invenio-oauthclient/issues/115), I'm bumping to
the latest release.
=> setup: Flask-WTF version bump

cds/modules/deposit/static/templates/cds_deposit/types/common/uploader.html
* Hides the subformats from the files list when is empty. (closes #831)
=> deposit: hide subformats from the list when empty

cds/modules/records/serializers/drupal.py
* Fixes issue with the Drupal serializer searching for a key in keyword
objects that is not preserved on `marshmallow ` (de)serialization.
(closes #838)
=> deposit: drupal export fix

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsActions.js
* Fixes issue, where the UI deleted a video without updating the parent
project's references. (closes #795)
=> deposit: delete video fix

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js, cds/modules/deposit/static/json/cds_deposit/forms/video.json, cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/array.html
* Fixes issue, where a form was still `pristine` (i.e. not `dirty`),
after reordering an array's elements. (closes #705)
=> deposit: proper form state after array reordering

cds/modules/ffmpeg/ffmpeg.py, cds/modules/webhooks/tasks.py
* ffmpeg: remove EOS specific code.
* webhooks: add retry to ffmpeg tasks.
[deployed]
=> Celery retry

cds/modules/deposit/static/templates/cds_deposit/types/video/action_delete.html
* Adds a user confirmation modal window to confirm video delete.
(closes #855)
=> deposit: user confirmation on video delete

cds/modules/webhooks/tasks.py, tests/unit/conftest.py, tests/unit/test_webhook_tasks.py
* When the tasks fails there is no `extracted_metadata` key to delete and therefore the clean method raises, this exception should only happen in this situation.
=> webhooks: prevent extract metadata clean failure

cds/modules/records/serializers/schemas/common.py
* Changes the minumum number of characters in the ``title`` from 3 to 4.
(closes #848)
=> serializers: change minimum title length

cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/uiselect.html
* Sets minimum input lenght for autocomplete author field.
(closes #849)
=> deposit: set minimum input lenght for autocomplete

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
* Correctly disable/enable description field when the deposit is
published/unpublished. (closes #850)
=> deposit: consistent description disabling

cds/modules/search_ui/static/templates/cds_search_ui/results.html, cds/modules/theme/static/templates/cds/video/featured-medium.html, cds/modules/theme/static/templates/cds/video/medium.html, cds/modules/theme/static/templates/cds/video/small.html
* Removes one-time angular binding from search results. (fixes #896)
=> search: one-time binding fix

cds/modules/deposit/static/templates/cds_deposit/types/project/form.html, cds/modules/deposit/static/templates/cds_deposit/types/video/form.html
* Disable the editing of access rights when a deposit is published.
(closes #908)
=> deposit: disabled access rights when published

cds/modules/deposit/static/templates/cds_deposit/types/video/form.html
* Adds an error to the file tab if there is an error with the
transcodings. (closes #926)
=> deposit: file tab error

cds/modules/deposit/api.py
* Raises a validation error with a meaningful message if the category and/or the type is missing from the project when publishing a video. (closes #863)
=> deposit: better category/type missing error

cds/modules/deposit/api.py, cds/modules/fixtures/cli.py, cds/modules/records/serializers/schemas/video.py, cds/modules/webhooks/receivers.py, cds/modules/webhooks/views.py, tests/data/test_videos_projects.json, tests/unit/conftest.py, tests/unit/helpers.py, tests/unit/test_deposit_validation.py, tests/unit/test_project.py, tests/unit/test_project_rest.py, tests/unit/test_serializer.py, tests/unit/test_webhook_receivers.py, tests/unit/test_webhook_views.py
* Adds receiver permissions to have the same behaviour of deposit.
(closes #869)
* Fixes synchronization of access rights from project to video.
(addresses #889)
* Fixes contributors on tests.
=> webhooks: receiver permissions addition, fix access rights on video, set video owner always project owner 

cds/modules/webhooks/tasks.py, tests/unit/conftest.py, tests/unit/helpers.py, tests/unit/test_webhook_receivers.py, tests/unit/test_webhook_tasks.py, tests/unit/test_webhook_views.py
* Ignores videos with too high resolutions. (closes #949)
=> webhooks: ignore videos with too high resolutions

cds/modules/deposit/api.py, cds/modules/deposit/mappings/deposits/records/videos/project/project-v1.0.0.json, cds/modules/deposit/mappings/deposits/records/videos/video/video-v1.0.0.json, cds/modules/webhooks/tasks.py, tests/unit/helpers.py, tests/unit/test_deposit.py, tests/unit/test_migration.py, tests/unit/test_webhook_tasks.py
* Separates function to check if the deposit is published from
the function to check if a record exists.
* Does't remove file instance when object version is removed.
* Temporary skip test on record files migration because of cds-dojson.
=> deposit: fix republishing when workflow pending

cds/config.py, tests/unit/test_celery.py
* Uses cron instead of time delta for scheduled tasks. (closes #909)
=> config: use cron for scheduled tasks

cds/modules/records/static/templates/cds_records/video/detail.html, cds/modules/records/templates/cds_records/record_detail.html, cds/modules/stats/views.py, setup.py
In order to test it, it requires a reverse proxy server (e.g. w/nginx) to query the ES cluster in production.
Also see cds-js/PR#11.
* Adds a new (legacy) module to query the number of views from the ES
cluster in production and display them in the record page.
(closes #928)
* Depends on the corresponding PR in cds-js.
Signed-off-by: Jose Benito Gonzalez Lopez <jose.benito.gonzalez@cern.ch>
=> global: addition of number of record views

cds/config.py, cds/modules/migrator/cli.py, cds/modules/migrator/records.py, tests/unit/test_migration.py
* Adds `modified_by` on serializer.
* Converts the modified_by in the user_id. (addresses #991)
* Fixes smil file creation. (closes #1058)
* Adds the resolution tag on slaves. (closes #1059)
* Adds a new migration command to update sequence counter after
migration. (closes #993)
=> migration: add resolution tag to the slaves, fix smil file creation, update sequence counter

cds/modules/records/static/templates/cds_records/video/detail.html
* Removes the one-time binding as it won't work in combination with the
default values.
=> records: fix for copyright year and holder

cds/modules/theme/static/templates/cds/video/small.html
* Fixes the problem when one of the elements in the search results is
longer than the others in the same row (and it's not the last element
of the row), then the next row is badly aligned (as described here:
https://getbootstrap.com/docs/3.3/css/#grid-responsive-resets).
=> theme: fix search results alignment

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js, cds/modules/deposit/static/templates/cds_deposit/types/video/form.html
* Adds force inherit metadata options, a modal is appearing and let
the user select if they want to inherit only the missing fields or
replace all the medata. (closes #1034)
=> deposit: addition of force inherit metadata

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js, cds/modules/webhooks/receivers.py, cds/modules/webhooks/status.py, cds/modules/webhooks/tasks.py, requirements.topical.branches.txt, tests/unit/conftest.py, tests/unit/helpers.py, tests/unit/test_webhook_receivers.py, tests/unit/test_webhook_tasks.py, tests/unit/test_webhook_views.py
* Improves re-upload of master file, marking as deleted the old event
and create a new one.
* Improves error handling if exception occur on a task.
* Soft-delete files in case of clean to avoid merge conflict. (closes #1112)
=> deposit: delete old event if reupload master

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js, cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/strapselect.html, cds/modules/deposit/static/templates/cds_deposit/types/project/actions.html, cds/modules/deposit/static/templates/cds_deposit/types/video/actions.html
* Adds the option to display legacy ``type``, when the project is saved
with a different ``type`` and refresh the page, the type will disappear
from the list.
* Removes validation check on ``Edit`` buttons, now no matter if the
deposit is valid or not the user will be able to edit it.
=> deposit: addition of legacy types

cds/modules/records/static/templates/cds_records/video/downloads.html
I left the title `Files`, it probably makes sense. Let me know if you want to remove that one too.
=> global: removed misleading text on record download

cds/modules/records/symlinks.py
Tested directly in `cdslabs_qa` celery task server, and it is now creating the right symlinks.
=> global: fixed symlinks locations by replacing xrootd path

cds/modules/deposit/static/json/cds_deposit/forms/video.json
* Removes `Materials` field from the first license. (closes #1175)
=> deposit: fix of licenses

cds/modules/deposit/static/templates/cds_deposit/deposits.html
* Hides the ``+ Add videos`` button from the deposit page when the
project is ``published``, the user should first click the ``Edit``
button for the button to be visible. (closes #1169)
=> deposit: hide add videos button

cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js, cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
* Adds ``translations`` as part of the inherit functionality.
(closes #1200)
* Adds ``Internal Server Error`` message on alerts when there is
a 5XX HTTP status.
=> deposit: inherit translations

cds/modules/migrator/records.py, cds/modules/migrator/utils.py, cds/modules/webhooks/tasks.py, tests/unit/helpers.py, tests/unit/test_migration.py
* Adds missing subformats creation on migration. (closes #1201)
(closes #1199)
=> migrator: create missing subformats

cds/config.py, cds/modules/records/api.py, cds/modules/redirector/views.py, requirements.pinned.txt, setup.py, tests/unit/conftest.py, tests/unit/test_records.py
Still missing tests.
@egabancho for the `def drupal_export_alias():` I am parsing the url we define in the `config.py` with regex, but I am not sure it is worth. Do you prefer to hardcod the url instead?
=> global: fixed drupal export routing

cds/modules/deposit/bundles.py, cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js, cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js, cds/modules/deposit/static/js/cds_deposit/main.js, cds/modules/deposit/templates/cds_deposit/index.html, cds/modules/theme/static/scss/cds.scss, cds/modules/theme/templates/cds_theme/footer.html
This should fix the layout issues on cds videos + add a warning on cds deposit.
@drjova I had to remove a couple of destructuring assignment because otherwise I cannot have a js function with IE11 to detect the browser version... IE11 does not support it and blocks the js execution :(
=> global: css/js fixed for IE support

cds/modules/records/mappings/categories/category-v1.0.0.json
* the ES mapping for the field `_access` was missing: the field must
have `index: not_analyzed` set to get results when using filtered
queries with terms.
* fixes #1252
=> deposit: fixed wrong list of categories in deposit form

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js, cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js, cds/modules/deposit/static/templates/cds_deposit/deposits.html, cds/modules/deposit/static/templates/cds_deposit/types/common/uploader.html, cds/modules/deposit/static/templates/cds_deposit/types/project/actions.html, cds/modules/deposit/static/templates/cds_deposit/types/project/form.html, cds/modules/deposit/static/templates/cds_deposit/types/video/form.html, cds/modules/theme/static/scss/cds.scss
* Adds alert when the user try to reload the page and there are
unsaved changes.
* Fixes issue with stucked overall status. Now only displays the overall
status from ``_cds`` which backend sends. (closes #1231)
* Adds a help text to translation tab for subtitles. (closes #1268)
=> deposit: improves forms

cds/modules/webhooks/tasks.py
* Stops the celery task if the transcoding in sorenson was canceled.
=> webhooks: stop task on canceled transcoding job

cds/modules/cds_iiif/utils.py
* Reads image files in binary mode (otherwise Python3 throws
exceptions).
In Python 3 you can get this kind of errors: https://github.com/python-pillow/Pillow/issues/1605 if the images are not opened as binaries.
=> cds-iiif: open image in 'rb' mode

cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js, cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js, cds/modules/deposit/static/templates/cds_deposit/types/common/uploader.html, cds/modules/deposit/static/templates/cds_deposit/types/video/uploader.html
* Adds version to the URL of each thumbnail. That way, the browser
won't cache them. Before this fix, thumbnails were automatically
cached, so after replacing the video with a new one, the new
thumbnails were not shown. There is no need to handle this version
parameter in the IIIF, it's used just to prevent browser caching.
=> deposit: add version to thumbnails URLs

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsActions.js, cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js, cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js, cds/modules/deposit/static/json/cds_deposit/forms/project.json, cds/modules/deposit/static/templates/cds_deposit/types/project/form.html
- category and type fields are disabled if at least one video was
previously published.
- project and videos are saved on category/type change and forms are
reset to pristine.
- closes #1294
- closes #1297
=> deposit: block category/type if video published

cds/modules/deposit/static/templates/cds_deposit/types/project/form.html, cds/modules/deposit/static/templates/cds_deposit/types/video/form.html
* Removes the exclamation mark from the tabs, because
angular-schema-form handles ``$invalid`` not intuitively.
(closes #1289)
=> deposit: remove exclamation mark

cds/modules/migrator/records.py
* Removed `duration` kwarg parameter because it is returned by the
ExtraFrameTask._time_position() method call and therefor contained
in the `options` dict.
=> migrator: fix duplicated frame duration kwarg

cds/modules/theme/templates/cds_theme/header.html
* If ``DEBUG`` is ``False`` the login button redirects directly to
CERN oauth2 provider.
=> global: login redirects to CERN provider

cds/modules/ffmpeg/ffmpeg.py, tests/unit/test_webhook_tasks.py
* When minor errors occur while running ffprobe `-v error` prints them embedded on the JSON output, making loading the result fail. Decreasing the level to `quiet` and checking the output seems a better solution.
=> ffmpeg: set ffprobe verbosity to quiet

cds/config.py, cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js, cds/modules/records/templates/cds_records/record_detail.html
- fixed UnicodeEncodeError on record details view when keywords contains
non ASCII chars.
- fixed deposit ui which fails when searching for keywords with non
ASCII chars.
- removed all dangerous .format() from Jinja2 templates because it
breaks when formatting unicode strings
- See: https://github.com/pallets/jinja/issues/392
- addresses #1332
=> ui: fixed encoding issues

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js
* Fixes the previewer to preview the new file, after it has been
replaced.
=> deposit: preview the replaced file

cds/modules/cds_iiif/utils.py, cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js
* Fixes the problem that thumbnails for frames were not updated if the
video was replaced - it was caused by the fact, that the key used in
redis for caching was using the filename, and the file name doesn't
change if we replace the video in the deposit (but the version of the
file changes, so we are adding it to the cache key).
=> iiif: thumbnails cache busting

requirements.pinned.txt
* Removes invenio-files-rest from pinned dependencies as it is already
in the requirements.topical.branches.
=> requirements: remove invenio-files-rest

cds/modules/migrator/tasks.py, tests/unit/test_migration.py
* The on_success method runs outside application context raising an exception. Overloading the run method adding the extra code seems to work correctly.
=> migrator: fix TranscodeVideoTaskQuiet task

cds/modules/records/static/templates/cds_records/keywords.html, cds/modules/records/templates/cds_records/record_detail.html
* Fixed the links of the keywords on the record_detail page, so their
URLS have a correct search query (closes #1435).
=> templates: fix keywords links

cds/modules/redirector/views.py
* Old embeded videos pointing to project's report number, that causing
404 in the new system. With this fix if the report number belongs to
a project, it will automatically redirect to the first video.
Co-authored-by: Esteban J. G. Gabancho <esteban.gabancho@gmail.com>
=> redirector: fix redirect on project report number

cds/modules/webhooks/tasks.py
When running the transcode task it can happen that the aspect ratio is  not in the list and therefore needs to be change by the closest one. We call use the display_aspect_ratio to call several API function so it might be better to fix it from the beginning.
**NOTE**: this is a hack until CERNDocumentServer/cds-sorenson#37 is fixed.
=> webhooks: use closest aspect ratio to transcode

cds/modules/ffmpeg/ffmpeg.py
Added the `-qscale` parameter for the video `:v` with the quality `1` (1 - 33, 33 being the lowest quality)
Closes #1453
=> ffmpeg: fix low quality in extracted frames

cds/config.py, cds/modules/deposit/api.py, cds/modules/ffmpeg/ffmpeg.py, cds/modules/fixtures/data/pages/faq.html, cds/modules/fixtures/data/videos/ATLAS-VIDEO-2017-013.json, cds/modules/maintenance/__init__.py, cds/modules/maintenance/cli.py, cds/modules/maintenance/subformats.py, cds/modules/maintenance/tasks.py, cds/modules/migrator/cli.py, cds/modules/migrator/records.py, cds/modules/migrator/tasks.py, cds/modules/migrator/utils.py, cds/modules/webhooks/receivers.py, cds/modules/webhooks/tasks.py, requirements.pinned.txt, setup.py, tests/unit/conftest.py, tests/unit/helpers.py, tests/unit/test_deposit.py, tests/unit/test_ffmpeg.py, tests/unit/test_maintenance.py, tests/unit/test_migration.py, tests/unit/test_webhook_receivers.py, tests/unit/test_webhook_tasks.py, tests/unit/test_webhook_views.py
* use the new cds_sorenson api to transcode videos also in case of
unsopported aspect ratio
* remove `slave` filename
* create new maintenance module to allow subformat creation by using the
shell or the command line
* closes #1520
=> maintenance: new module for recurrent admin tasks

cds/modules/home/templates/cds_home/home.html, cds/modules/records/templates/cds_records/record_detail.html, cds/modules/search_ui/templates/cds_search_ui/search.html
* `disable-url-handler` config disables all
url parameters and thus deep links and
search is broken. It was added in the first
place just to hide the page size from url.
=> search: Revert back disable url handler

cds/modules/records/templates/cds_records/record_detail.html
* Lucene syntax requires that operator, like AND or OR, are uppercase to
be considered as such. Also to adding parenthesis to the keywords
makes the query more meaningful.
=> records: fix related records queries

cds/modules/theme/static/js/main.js
This addresses https://github.com/CERNDocumentServer/cds-videos/issues/1588. No need of having quotes if `bestmatch` sorting is done correctly.  Currently the sort option seems to be working but we need to test it more.
=> search: trigger search on suggestion selection

cds/modules/previewer/templates/cds_previewer/macros/player.html, cds/modules/records/serializers/smil.py, tests/unit/conftest.py, tests/unit/test_serializer.py
The fix it's basically moving the 720p video subformat at the top in the smill file.
If there is no 720p video subformat then then it will load the 480p. 
If the 480p subformat is missing also then it will leave the smill file as it is.
Closes #1570
=> Fix initial video rendition

cds/config.py
=> config: change no-reply email to no-reply@cern.ch

cds/modules/files/receivers.py, cds/modules/previewer/extensions/video.py
* add missing file extensions for video master files to be able to play
the video.
* avoid prepending report number to filename when donwloading if already
correctly named.
=> previewer: add missing video extensions

cds/config.py, cds/modules/deposit/templates/cds_deposit/index.html, cds/modules/search_ui/static/templates/cds_search_ui/error.html
* Sometimes there was an empty error panel shown
in search results. Now also checking the message
of the error not to be empty.
closes #1560
=> search: fix search ui error

cds/modules/records/tasks.py
* Fixes the problem with the file integrity report caused by wrong
format passed to the format_pid_link function.
=> tasks: fix file integrity report

cds/modules/fixtures/data/categories.json
* Adds responsible egroups for ATLAS, CMS and SCADA in order to be able to share the deposit.
(closes #1583 )
=> Fixtures: Additional responsible egroups for deposits

cds/modules/fixtures/data/pages/faq.html, cds/modules/previewer/templates/cds_previewer/macros/player.html
Adds option to activate subtitles by default on embedded videos.
Tested in cdslabs_qa, it works.
=> player: option to activate subtitles by default

cds/modules/webhooks/tasks.py
[related to RQF1344597]
* When the transcoding is done, the checksum is calculated. Replaced
reading the whole file vs reading in chunks (using the default
files_rest method for it).
Co-authored-by: Alexander Ioannidis <a.ioannidis@cern.ch>
=> transcoding: fixed checksum calculation

cds/modules/flows/api.py
- Videos with 'uri' and no 'version_id' were not getting downloaded because 'version_id' was being generated before calling the download task on celery.
=> Remote upload

cds/config.py, cds/modules/previewer/templates/cds_previewer/macros/player.html, cds/modules/previewer/templates/cds_previewer/video/video.html, tests/unit/conftest.py, tests/unit/test_previewer.py
* uses license key instead of built SDK only
=> player: add theoplayer license as config

cds/modules/invenio_deposit/api.py
* the `_cds.current_user_mail` has been removed, however it might still be present in some previous records' revisions. This makes the publishing of editing videos fail. When the `_cds.current_user_mail` is found while publishing, it is ignored.
=> deposit: remove old user email when present

cds/modules/deposit/api.py, cds/modules/fixtures/data/pages/faq.html, cds/modules/maintenance/cli.py, cds/modules/records/minters.py, tests/unit/test_provider.py, tests/unit/test_video_rest.py
- Removed DOI minting code for video
- Added a CLI command to mint DOI
- Updated FAQ section to request a DOI
- Updated tests to reflect the changes
=> make DOI optional and add CLI command for DOI minting

cds/modules/deposit/api.py, tests/unit/test_project_rest.py
Update `Project/create` method to include existing `_access.update` values in data
=> Enhance '_access.update' to include existing values

Bruno Collection - CDS Videos Publish Video.json, README.rst
- Added Table of Contents to the README for better navigation.
- Included the new Publish Video through REST API section in the README with detailed steps.
- Added the exported Bruno REST API collection to the repository.
=> Update README and Add Bruno Collection for REST APIs

.github/workflows/tests.yml, cds/config.py, cds/modules/oauthclient/cern_openid.py, cds/modules/theme/templates/cds_theme/header.html
* Change app name to avoid collisions with the cern_openid in invenio-oauthclient. Signals on_identity_* won't be called in Invenio module.
=> oauth: change app name

Bruno Collection - CDS Videos Publish Video.json, README.rst, cds/modules/deposit/api.py, cds/modules/deposit/ext.py, cds/modules/deposit/static/templates/cds_deposit/deposits.html, cds/modules/deposit/static/templates/cds_deposit/types/video/uploader.html, cds/modules/records/static/templates/cds_records/video/downloads.html, cds/modules/theme/assets/bootstrap3/js/cds/module.js, cds/modules/theme/assets/bootstrap3/js/cds_deposit/avc/components/cdsUploader.js, cds/modules/theme/assets/bootstrap3/scss/cds/cds.scss, tests/unit/test_video_rest.py
**Current Behavior:**
- When a video file is uploaded as a complimentary (additional) file, it replaces the master file and triggers the workflow.
All files are tagged as `subtitle` after upload
**UI Changes:**
- Separated the functionality for uploading additional files and replacing the master file.
- Updated the UI to reflect these distinct behaviors:
- Replacing the Master File: Continues to trigger the workflow as before.
- Uploading Additional Files: Behaves as expected, uploads the file as an additional file without triggering the workflow.
-  Landing page files are displaying in this order:
- Other video formats
- Thumbnails
- Subtitles
- Additional video files (new)
- Other files (new)
**Backend Changes:**
- Modifed the `create_tags` method to support additional files, this also …
=> support uploading additional video files

cds/modules/records/serializers/schemas/common.py
The source field was missing from marshmallow schema and this causing old migrated records unable to be published after editing. In the current version of the codebase the source is not kept but all keywords are added as free text.
=> keywords: add missing source field used in old migrated records

cds/modules/deposit/api.py, tests/unit/test_video.py
Only this line changed from the master branch:
https://github.com/CERNDocumentServer/cds-videos/blob/main/cds/modules/deposit/api.py#L872
When removing the `subtitle_obj`, it was also removing the `ObjectVersionTag`s, so tags were not actually copied.
=> subtitles: fix renaming on publish

cds/modules/deposit/mappings/os-v2/deposits/records/videos/video/video-v1.0.0.json, cds/modules/deposit/schemas/deposits/records/videos/video/video-v1.0.0.json, cds/modules/records/mappings/os-v2/records/videos/video/video-v1.0.0.json, cds/modules/records/schemas/records/videos/video/video-v1.0.0.json, cds/modules/records/serializers/schemas/common.py, cds/modules/records/serializers/schemas/video.py
closes https://github.com/CERNDocumentServer/cds-videos/issues/2035
closes https://github.com/CERNDocumentServer/cds-videos/issues/2031
- `volumes` is added to `_curation`
- `additional_titles` added
- `additional_descriptions` added
- `related_identifiers` added
=> schema: add related_identifiers and additonal titles/descriptions

.github/workflows/tests.yml, tests/unit/test_fixtures.py, tests/unit/test_schema_datacite.py
Since we have the new category `LECTURES`  test `test_fixture_categories` was failing.
And we added [`contributors`](https://github.com/CERNDocumentServer/cds-videos/blob/additional-files/cds/modules/records/serializers/schemas/datacite.py#L56) to datacite schema, `test_video_metadata_tranform` was failing.
Tests are fixed now
=> tests: fix failing tests

cds/modules/deposit/api.py, cds/modules/deposit/receivers.py, cds/modules/flows/api.py, cds/modules/flows/tasks.py, cds/modules/previewer/templates/cds_previewer/macros/player.html, cds/modules/records/serializers/schemas/video.py, cds/modules/records/static/templates/cds_records/video/detail.html, cds/modules/records/static/templates/cds_records/video/share.html, cds/modules/records/utils.py, cds/modules/theme/assets/bootstrap3/js/cds/module.js, cds/modules/theme/assets/bootstrap3/js/cds_records/cdsRecord.js, cds/modules/theme/assets/bootstrap3/scss/cds/cds.scss, tests/unit/test_flows_tasks.py
-  https://optiview.dolby.com/docs/theoplayer/knowledge-base/playback/subtitles-and-closed-captions/chapter-markers/
Chapters are implemented similar to Youtube.
Chapters can be followed like transcriptions from the side
You can share the record with timestamp
=> feature: add chapters and task for chapter frames

cds/config.py, cds/modules/deposit/views.py, cds/modules/home/views.py, cds/modules/invenio_deposit/utils.py, cds/modules/invenio_deposit/views/ui.py, cds/modules/ldap/decorators.py, cds/modules/oauthclient/cern_openid.py, cds/modules/records/permissions.py, scripts/setup, setup.cfg, tests/unit/conftest.py, tests/unit/test_external_user.py
In SSO application:
- Role `cern-user` should change to **not** `required`
- Add new role with `Minimum Level of Assurance` and identifier `authenticated-user`.
- Enable: `This role is required to access my application` 
- Enable: `This role applies to all authenticated users`
Permissions:
- Users should have `cern-user` to upload/create.
- This role is connected with action: upload_access_action
```bash
cds access allow videos-upload-access role cern-user
```
TODO
=> auth: allow external accounts to login and restrict upload

.gitignore, cds/modules/deposit/api.py, cds/modules/fixtures/data/pages/faq.html, cds/modules/flows/tasks.py, cds/modules/records/utils.py, tests/unit/test_flows_tasks.py
Chapters timestamps should be unique, otherwise ffmpeg will fail and that will cause a loop for the task, it'll trigger itself.
- During sync we set `extract_chapters=False` so task can't trigger itself
- Parsing chapters method improved to return only unique timestamps
- During publish, instead of comparing chapters and chapter frames length, we'll compare the timestamps and if we're missing any it'll trigger the task
=> chapters: improve parsing with unique timestamps
