CERNDocumentServer/cds-videos

.kwalitee.yml

config: enable kwalitee

---

setup.py

installation: include `invenio-kwalitee`

---

cds/base/static/js/settings.js

base: update `settings.js` with the latest invenio

---

.travis.yml
README.rst

global: enable travis

---

setup.py

WIP:installation: add Flask-IIIF

---

cds/base/templates/header.html

template: fix logo broken link

---

cds/base/templates/cern_header.html

base: update sign in url from local to oauth

---

cds/base/recordext/fields/atlantis.cfg

Signed-off-by: Ivi Dimopoulou <ivi.dimopoulou@cern.ch>

recordext: fix typo

---

cds/base/bundles.py
cds/base/static/js/cds-settings.js
cds/base/static/js/personal/component/boxes.js
cds/base/static/js/personal/component/grid.js
cds/base/static/js/personal/helpers/boxStorage.js
cds/base/static/js/personal/helpers/settingsStorage.js
cds/base/static/js/personal/init.js
cds/base/static/js/personal/main.js
cds/base/static/js/personal/templates/edit/default.mustache
cds/base/static/js/personal/templates/edit/record_list.mustache
cds/base/static/js/personal/templates/error.mustache
cds/base/static/js/personal/templates/layout.mustache
cds/base/static/js/personal/templates/nav.mustache
cds/base/static/js/personal/templates/new.mustache
cds/base/static/js/personal/templates/normal/default.mustache
cds/base/static/js/personal/templates/normal/record_list.mustache
cds/base/static/js/personal/ui/box.js
cds/base/static/less/cds.less
cds/base/static/less/personal/main.less
cds/base/templates/search/index.html

wip: personal collections

---

cds/base/static/js/personal/component/boxes.js

personal_collection: remove unused dependency

---

.travis.yml

global: update .travis.yml

---

cds/base/bundles.py
cds/base/static/js/main.js
cds/base/static/js/record_tools.js
cds/base/static/js/templates/modal_list.mustache
cds/base/static/less/cds.less
cds/base/templates/helpers/general.html
cds/base/templates/records/metadata_base.html
cds/base/testsuite/__init__.py
cds/base/testsuite/js/fixtures/see_more_modal.html
cds/base/testsuite/js/test_pagination_see_more_modal.spec.js
cds/base/testsuite/js/test_see_more_modal.spec.js

* Template of a detail view
* Macros to convert parts of record to display on detail view
* Modal logic to display "see more..." popup for authors and keywords

template: add logic to display detail view of record

---

cds/base/static/js/record_tools.js
cds/base/templates/helpers/general.html

base: display `show all` only when necessary

---

cds/base/dojson/testsuite/test_cds_dojoson_videos.py
pytest.ini

dojson: video convert testing

---

.dockerignore
Dockerfile
INSTALL.rst
bower-base.json
docker-compose.yml
elasticsearch-docker.yml

* Adds the necessary Docker files.
* Builds on top of the `invenio-base` docker image.
* Allows usages of sudo.
* Updates the Install.rst.
Signed-off-by: David Zerulla <ddaze@outlook.de>

docker: initial release 

---

cds/modules/records/__init__.py
cds/modules/records/data/__init__.py

Signed-off-by: David Zerulla <ddaze@outlook.de>

global: travis fix, add missing docstrings

---

cds/config.py
requirements.baseline.txt

* Enables ``invenio-previewer``. (closes #92)

global: invenio-previewer addition

---

.eggs/README.txt
requirements.devel.txt
run-tests.sh

installation: travis build fix

---

MANIFEST.in

**We don't merge branches which don't have all tests passing unless we really understand the error in the tests**
--
@switowski

installation: fix MANIFEST.in

---

cds/config.py
cds/modules/home/templates/cds_home/home.html
cds/modules/records/bundles.py
cds/modules/records/static/js/cds_records/main.js
cds/modules/records/static/templates/cds_records/detail.default.html
cds/modules/records/templates/cds_records/record_detail.html
cds/modules/theme/static/js/cds-build.js
cds/modules/theme/static/js/main.js
cds/modules/theme/static/scss/cds.scss
setup.py

cds_records: ``cds-js`` integration

---

cds/modules/records/bundles.py
cds/modules/records/static/js/cds_records/main.js

cds_records: addition of ``angular-loading-bar``

---

cds/modules/theme/templates/cds_theme/footer.html

theme: fix typo in footer

---

tests/e2e/conftest.py
tests/e2e/test_frontpage.py
tests/e2e/test_search.py
tests/e2e/test_search_params.py

* Fixes e2e search test to wait for all facets to load.
* Adds a new e2e test for result filtering and the detailed view.

tests: improve selenium tests

---

setup.py

jsonschemas: update schemas location

---

cds/modules/records/mappings/records/album-v1.0.0.json
cds/modules/records/mappings/records/default-v1.0.0.json
cds/modules/records/mappings/records/image-v1.0.0.json
cds/modules/records/mappings/records/video-v1.0.0.json

mappings: fix for mappings

---

requirements.devel.txt
requirements.pinned.txt
setup.py

requirements: bump WTF

---

cds/modules/deposit/api.py
cds/modules/deposit/templates/cds_deposit/edit.html
cds/modules/deposit/views.py

Don't merge, it's not fully working and has a bunch of commits from other PR that I needed to make this work.

display already uploaded files

---

cds/config.py
cds/modules/records/minters.py
tests/unit/test_provider.py

config: fix deposit minter on record submission

---

cds/config.py
cds/modules/deposit/api.py
cds/modules/deposit/errors.py
tests/unit/conftest.py
tests/unit/demo/json_resolver.py
tests/unit/test_deposit.py
tests/unit/test_project.py
tests/unit/test_video.py

deposit: video and project publish implementation

---

cds/modules/webhooks/receivers.py
cds/modules/webhooks/tasks.py
setup.py
tests/unit/test_webhooks.py

webhooks: make 'key' download parameter optional 

---

cds/config.py
cds/modules/deposit/api.py
tests/unit/conftest.py
tests/unit/test_project.py
tests/unit/test_project_rest.py
tests/unit/test_video.py

* Implements video and project delete. (closes #259)

deposit: video and project delete implementation, REST API configuration

---

cds/config.py
cds/modules/deposit/static/json/cds_deposit/forms/project.json
cds/modules/deposit/static/templates/cds_deposit/alert.html
cds/modules/deposit/static/templates/cds_deposit/ckeditor.html
cds/modules/deposit/static/templates/cds_deposit/datepicker.html
cds/modules/deposit/static/templates/cds_deposit/search/results.html
cds/modules/deposit/static/templates/cds_deposit/uiselect.html
cds/modules/deposit/templates/cds_deposit/edit.html
cds/modules/deposit/templates/cds_deposit/index.html

deposit: general improvements

---

cds/modules/webhooks/helpers.py
cds/modules/webhooks/receivers.py
cds/modules/webhooks/task_classes.py
cds/modules/webhooks/tasks.py
cds/modules/webhooks/views.py
requirements.devel.txt
setup.py
tests/unit/conftest.py
tests/unit/test_access.py
tests/unit/test_cds.py
tests/unit/test_provider.py
tests/unit/test_webhook_helpers.py
tests/unit/test_webhooks.py

* Updates deposit status whenever a Celery task starts and completes. 
(closes #224)
* Depends on #268.

webhooks: deposit status update for tasks

---

cds/modules/webhooks/receivers.py
cds/modules/webhooks/task_classes.py
cds/modules/webhooks/tasks.py
cds/modules/webhooks/views.py
requirements.devel.txt
setup.py
tests/unit/conftest.py
tests/unit/test_webhooks.py

* Orders tasks in a workflow for progress reports. (closes #266)
* General code refactoring.

webhooks: ordered tasks and refactoring

---

requirements.devel.txt

* Updates developer requirement for invenio-webhooks.

global: webhooks requirement update

---

.travis.yml

Signed-off-by: Esteban J. G. Gabancho <esteban.gabancho@gmail.com>

travis: ES mapper-attachment plugin

---

cds/modules/deposit/api.py
tests/unit/test_project_rest.py

* Adds _files to the record serializer. (closes #299)

deposits: add _files to the serializer

---

cds/modules/webhooks/tasks.py
tests/unit/conftest.py
tests/unit/test_deposit.py
tests/unit/test_project.py
tests/unit/test_project_rest.py
tests/unit/test_webhook_receivers.py

webhooks: fix on record update celery task

---

cds/modules/webhooks/tasks.py

* Commits changes to the files faster so the UI gets the list of files
attached to a deposit as soon as possible. (closes #309)

webhooks: faster transcoded files commit

---

cds/modules/webhooks/receivers.py
cds/modules/webhooks/tasks.py
requirements.devel.txt
tests/unit/test_webhook_receivers.py

* Adds links to the downloader response for `self`, `version` and
`cancel`. It is up to the UI to decide which one to use depending
on the status of the event.

webhooks: downloader event links

---

cds/modules/webhooks/tasks.py
scripts/setup-npm.sh
tests/unit/test_deposit.py
tests/unit/test_webhook_receivers.py
tests/unit/test_webhook_tasks.py

Node sass version

---

cds/modules/webhooks/receivers.py
cds/modules/webhooks/tasks.py
tests/unit/test_deposit.py

webhooks: fix tasks name

---

cds/modules/deposit/api.py
cds/modules/webhooks/receivers.py
tests/unit/test_webhook_receivers.py

WIP webhooks: fix object_version detached from session

---

cds/modules/webhooks/tasks.py

* Fixes minor issue with percentage calculation.

webhooks: frames percentage fix

---

cds/config.py
cds/modules/deposit/api.py
cds/modules/deposit/fetchers.py
cds/modules/deposit/mappings/categories/category-v1.0.0.json
cds/modules/deposit/minters.py
cds/modules/fixtures/cli.py
cds/modules/fixtures/data/categories.json
setup.py
tests/unit/conftest.py
tests/unit/test_category.py
tests/unit/test_fixtures.py

* Fixes json query on events.
* Adds category as new record type with its own schema and mapping.
* Configure suggester to autocomplete names. (closes #183)

deposit: category addition

---

requirements.devel.txt
requirements.pinned.txt
setup.py

requirements: temporary removal of i18n

---

cds/modules/deposit/mappings/deposits/records/project-v1.0.0.json
cds/modules/deposit/mappings/deposits/records/video-v1.0.0.json
cds/modules/records/mappings/records/project-v1.0.0.json
cds/modules/records/mappings/records/video-v1.0.0.json

mappings: addition of `extracted_metadata`

---

cds/modules/deposit/api.py
tests/unit/conftest.py
tests/unit/test_deposit.py

deposit: fix state initialization

---

requirements.pinned.txt
setup.py

- updates version requirements for invenio-accounts, invenio-files-rest
Signed-off-by: Sourabh Lal sourabhlal@gmail.com

update version requirements

---

cds/config.py
cds/modules/deposit/api.py
cds/modules/deposit/bundles.py
cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsActions.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsRemoteUploader.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js
cds/modules/deposit/static/js/cds_deposit/avc/factories/states.js
cds/modules/deposit/static/js/cds_deposit/cdsDeposit.module.js
cds/modules/deposit/static/templates/cds_deposit/deposits.html
cds/modules/deposit/static/templates/cds_deposit/list.html
cds/modules/deposit/static/templates/cds_deposit/remote_upload.html
cds/modules/deposit/static/templates/cds_deposit/types/common/uploader.html
cds/modules/deposit/static/templates/cds_deposit/types/project/form.html
cds/modules/deposit/static/templates/cds_deposit/types/video/actions.html
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html
cds/modules/deposit/templates/cds_deposit/edit.html
cds/modules/previewer/api.py
cds/modules/previewer/static/css/cds_previewer/video.css
cds/modules/previewer/templates/cds_previewer/video.html
cds/modules/previewer/views.py
cds/modules/theme/static/scss/cds.scss
cds/modules/webhooks/tasks.py
scripts/setup-instance.sh
setup.py
tests/unit/conftest.py
tests/unit/test_previewer.py

(closes https://github.com/CERNDocumentServer/cds/issues/172, https://github.com/CERNDocumentServer/cds/issues/167, https://github.com/CERNDocumentServer/cds/issues/228)

deposit: SSE UI implementation 

---

cds/modules/webhooks/receivers.py
tests/unit/test_webhook_receivers.py

* Fixes transcode/video_extract status.
* Receivers refactoring.

webhooks: receivers refactoring

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js
cds/modules/deposit/static/templates/cds_deposit/types/common/uploader.html

* Shows subformats in a collapsible accordion list. (closes #360)

deposit: accordion list for video slaves

---

cds/modules/deposit/api.py
cds/modules/records/mappings/records/project-v1.0.0.json
cds/modules/records/mappings/records/video-v1.0.0.json
cds/modules/records/minters.py
cds/modules/records/providers.py
cds/modules/records/serializers/schemas/json/common.py
cds/modules/records/serializers/schemas/project.py
cds/modules/records/serializers/schemas/video.py
requirements.devel.txt
setup.py
tests/unit/conftest.py
tests/unit/test_deposit.py
tests/unit/test_project.py
tests/unit/test_project_rest.py
tests/unit/test_report_number_generation.py
tests/unit/test_video.py

deposit: categogy/type of projects, report number

---

cds/modules/webhooks/receivers.py
cds/modules/webhooks/status.py
cds/modules/webhooks/tasks.py
cds/modules/webhooks/views.py
setup.py
tests/unit/conftest.py
tests/unit/helpers.py
tests/unit/test_deposit.py
tests/unit/test_webhook_receivers.py
tests/unit/test_webhook_status.py
tests/unit/test_webhook_tasks.py
tests/unit/test_webhook_views.py

webhooks: task start/stop endpoint

---

cds/modules/deposit/api.py
requirements.devel.txt
tests/unit/conftest.py
tests/unit/demo/json_resolver_required_fields.py
tests/unit/test_deposit.py
tests/unit/test_fixtures.py
tests/unit/test_project.py

* Introduces partial validation. (closes #324)

deposit: default partial validation on commit

---

cds/modules/deposit/api.py
cds/modules/webhooks/receivers.py
cds/modules/webhooks/tasks.py
tests/unit/conftest.py
tests/unit/test_webhook_receivers.py

* Proper API requests. (closes #377)
* Non-fatal error on invalid resolutions.

webhooks: Sorenson fixes

---

cds/modules/webhooks/receivers.py
cds/modules/webhooks/tasks.py
tests/unit/conftest.py
tests/unit/test_webhook_receivers.py

webhooks: fix AVC workflow on local file

---

.coveragerc
MANIFEST.in
cds/modules/deposit/api.py
cds/modules/webhooks/status.py
tests/unit/conftest.py
tests/unit/test_project.py

deposit: check tasks status on video publish

---

cds/modules/deposit/api.py
tests/unit/conftest.py
tests/unit/helpers.py
tests/unit/test_project.py
tests/unit/test_video.py

deposit: clean tasks result of video delete

---

cds/modules/deposit/api.py
cds/modules/webhooks/receivers.py
cds/modules/webhooks/tasks.py
tests/unit/helpers.py
tests/unit/test_project.py

webhooks: update project tasks status

---

cds/modules/fixtures/cli.py
scripts/setup-instance.sh
tests/unit/test_fixtures.py

fixtures: sequence generator addition

---

cds/config.py
cds/modules/deposit/api.py
cds/modules/deposit/ext.py
cds/modules/deposit/receivers.py
setup.py
tests/unit/test_project_rest.py

deposit: project and video indexing on publish

---

cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsActions.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js

deposit: fix JS syntax errors

---

MANIFEST.in
cds/config.py
cds/modules/deposit/api.py
cds/modules/records/serializers/smil.py
cds/modules/records/templates/cds_records/record_export.html
cds/modules/records/templates/cds_records/records_export_unsupported.html
cds/modules/records/templates/cds_records/video.smil
cds/modules/records/views.py
setup.py
tests/unit/conftest.py
tests/unit/helpers.py
tests/unit/test_project.py
tests/unit/test_records.py
tests/unit/test_serializer.py
tests/unit/test_video.py

* added export endpoint
* added json export format
Signed-off-by: Sourabh Lal sourabhlal@gmail.com

records: addition of export functionality

---

cds/modules/webhooks/tasks.py
tests/unit/helpers.py
tests/unit/test_webhook_status.py
tests/unit/test_webhook_tasks.py

* Creates GIF when all video frames have been generated. (closes #392)

webhooks: GIF generation

---

MANIFEST.in
cds/config.py
cds/modules/records/serializers/__init__.py
cds/modules/records/serializers/smil.py
cds/modules/records/serializers/vtt.py
cds/modules/records/templates/cds_records/thumbnails.vtt
tests/unit/conftest.py
tests/unit/test_records.py
tests/unit/test_serializer.py

* Adds vtt export format and serializer to be used to export thumbnails for videos.
* Adds tests for vtt serializer
Signed-off-by: Sourabh Lal sourabhlal@gmail.com

records: addition of vtt serializer and tests

---

cds/modules/ffmpeg/ffmpeg.py
cds/modules/webhooks/tasks.py
cds/modules/webhooks/views.py
setup.py
tests/unit/conftest.py
tests/unit/helpers.py
tests/unit/test_ffmpeg.py
tests/unit/test_previewer.py
tests/unit/test_video.py
tests/unit/test_webhook_tasks.py

* Added correct default arguments for frame extraction. (closes #396)
* Updated corresponding tests.

webhooks: frame extraction fix

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js

* Multiple stages of the overall status can be in progress at once.
* Out-of-order SSE events do not revert stages to the previous status.

deposit: overall status fixes

---

cds/modules/webhooks/tasks.py
tests/unit/test_project_rest.py
tests/unit/test_webhook_tasks.py

webhooks: fix metadata save after extraction

---

cds/modules/deposit/api.py
cds/modules/deposit/ext.py
cds/modules/deposit/indexer.py
cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js
cds/modules/webhooks/tasks.py
tests/unit/conftest.py
tests/unit/helpers.py
tests/unit/test_deposit.py
tests/unit/test_project.py
tests/unit/test_video.py
tests/unit/test_webhook_receivers.py
tests/unit/test_webhook_views.py

deposit: tasks status computed online

---

cds/config.py
cds/modules/deposit/api.py
cds/modules/records/mappings/records/project-v1.0.0.json
cds/modules/records/mappings/records/video-v1.0.0.json
cds/modules/records/serializers/__init__.py
cds/modules/records/serializers/drupal.py
cds/modules/records/serializers/schemas/json/common.py
cds/modules/records/serializers/schemas/project.py
cds/modules/records/serializers/schemas/video.py
requirements.devel.txt
tests/unit/conftest.py
tests/unit/test_records.py
tests/unit/test_serializer.py

records: drupal serializer addition

---

cds/modules/deposit/api.py
tests/unit/test_video.py

* Checks category and type on video publish. (closes #430)

deposit: check category and type on publish

---

cds/modules/webhooks/receivers.py
cds/modules/webhooks/status.py
cds/modules/webhooks/tasks.py
cds/modules/webhooks/views.py
tests/unit/conftest.py
tests/unit/helpers.py
tests/unit/test_webhook_receivers.py
tests/unit/test_webhook_views.py

webhooks: rerun tasks from endpoints improvements

---

requirements.devel.txt

installation: temporary use different oauthclient

---

cds/modules/fixtures/cli.py
cds/modules/home/templates/cds_home/home.html

* Adds flex to the home page. (addresses #454)

home: fix of content height

---

cds/modules/records/static/templates/cds_records/video/downloads.html
cds/modules/theme/bundles.py
cds/modules/theme/static/js/main.js

* Adds a separate section for downloading the master file.
* Removes almond js and the usages of require.

theme: video preview and download fixes

---

cds/config.py
cds/modules/deposit/bundles.py
cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js
cds/modules/deposit/static/json/cds_deposit/forms/project.json
cds/modules/deposit/static/json/cds_deposit/forms/video.json
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/checkbox.html
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/default.html
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/textarea.html
cds/modules/deposit/static/templates/cds_deposit/deposits.html
cds/modules/deposit/static/templates/cds_deposit/types/common/uploader.html
cds/modules/deposit/static/templates/cds_deposit/types/project/actions.html
cds/modules/deposit/static/templates/cds_deposit/types/project/form.html
cds/modules/deposit/static/templates/cds_deposit/types/video/action_delete.html
cds/modules/deposit/static/templates/cds_deposit/types/video/actions.html
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html
cds/modules/deposit/templates/cds_deposit/edit.html
cds/modules/theme/static/scss/cds.scss
cds/modules/theme/templates/cds_theme/page_cover.html

* Improves UI for deposit (closes #456, #457, #458, #438)

deposits: UI improvements

---

setup.py

installation: pin version of Flask-WTF==0.13.1

---

cds/modules/search_ui/static/templates/cds_search_ui/facets.html
cds/modules/search_ui/templates/cds_search_ui/search.html

* Removes the facets box when no results. (closes #459)

search_ui: fix facets box

---

cds/config.py
cds/modules/deposit/search.py

* Only show project deposits in the deposit list. (closes #440)

deposit: list of project deposits

---

cds/modules/deposit/templates/cds_deposit/index.html
cds/modules/search_ui/bundles.py
cds/modules/search_ui/templates/cds_search_ui/search.html
setup.py

search_ui: fix requirejs dependency

---

scripts/setup-instance.sh

installation: fix application name

---

requirements.devel.txt

installation: temporary cds-dojson branch removal

---

cds/modules/deposit/templates/cds_deposit/index.html
cds/modules/theme/static/js/main.js

* Removes deposit dependency from search module.

deposit: fix js dependencies

---

cds/config.py
cds/modules/deposit/static/json/cds_deposit/forms/video.json
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/checkbox.html
cds/modules/deposit/static/templates/cds_deposit/deposits.html
cds/modules/deposit/static/templates/cds_deposit/types/project/form.html

* Adds the checkbox template for angular-schema-form. (closes #461)

deposit: addition of checkbox template

---

cds/modules/deposit/static/json/cds_deposit/forms/video.json
cds/modules/records/mappings/records/video-v1.0.0.json
cds/modules/records/serializers/schemas/video.py

records: language field improvement

---

cds/modules/records/static/templates/cds_records/video/detail.html

* Shows the report number and DOI in the record detail page.
(closes #469)

record: report number and DOI

---

cds/modules/deposit/api.py
cds/modules/fixtures/cli.py
cds/modules/records/mappings/records/video-v1.0.0.json
cds/modules/records/serializers/drupal.py
cds/modules/records/serializers/schemas/video.py
cds/modules/webhooks/tasks.py
tests/unit/conftest.py
tests/unit/helpers.py
tests/unit/test_deposit.py
tests/unit/test_previewer.py
tests/unit/test_project.py
tests/unit/test_project_rest.py
tests/unit/test_records.py
tests/unit/test_report_number_generation.py
tests/unit/test_serializer.py
tests/unit/test_video.py
tests/unit/test_webhook_receivers.py

* Adds duration field for video records, which are calculated from the
video's extracted metadata and presents it in a human-readable way.
(closes #424)

records: duration field for video added

---

cds/modules/theme/templates/cds_theme/_macros.html
cds/modules/theme/templates/cds_theme/login_user.html

* Adds custom login page and redirect the users back to homepage when
the remote login is successful. (closes #451)

theme: addition of custom login page

---

cds/modules/records/serializers/schemas/json/common.py
cds/modules/records/serializers/schemas/project.py
cds/modules/records/serializers/schemas/video.py

serializers: addition of `translations` field

---

cds/modules/deposit/static/templates/cds_deposit/deposits.html
cds/modules/theme/static/scss/cds.scss
cds/modules/theme/templates/cds_theme/error/404.html

theme: fix font size in error pages

---

scripts/setup-instance.sh

@egabancho WDYT? It annoys me as I always forget it when I setup the instance.

installation: setup-instance add default location

---

cds/modules/records/static/templates/cds_records/video/detail.html

* Fixes broken css grid. (closes #508)

records: fix detail view grid

---

cds/modules/records/static/js/cds_records/main.js
cds/modules/records/static/templates/cds_records/video/downloads.html
cds/modules/records/static/templates/cds_records/video/share.html
cds/modules/theme/static/js/cds/module.js

* Adds the full `iframe` on the share embed field. (closes #506)
* Fixes the copy to clipboard button. (closes #510)

record: fix of embed share link

---

cds/modules/records/static/templates/cds_records/video/detail.html
cds/modules/theme/static/scss/decorators.scss

* Adds project link to the video page. (closes #515)

record: addition of project link

---

cds/modules/deposit/bundles.py
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/static/js/cds_deposit/avc/filters/overallState.js
cds/modules/deposit/static/templates/cds_deposit/search/results.html
cds/modules/theme/static/scss/cds.scss
cds/modules/theme/static/scss/variables.scss

* Fixes the project list with proper metadata. (closes #496)

deposit: update project list

---

cds/modules/deposit/static/templates/cds_deposit/types/common/uploader.html

* Display full uploaded file names and extracted format names on hover.
(closes #538)

deposit: file names on hover

---

cds/modules/theme/templates/cds_theme/footer.html

* Adds http:// to invenio-software link on footer. (fixes #553)

footer: correct invenio link

---

cds/config.py
cds/modules/deposit/api.py
cds/modules/fixtures/cli.py
cds/modules/previewer/api.py
cds/modules/records/serializers/smil.py
cds/modules/webhooks/tasks.py
tests/unit/conftest.py
tests/unit/helpers.py
tests/unit/test_previewer.py
tests/unit/test_project.py
tests/unit/test_project_rest.py
tests/unit/test_records.py
tests/unit/test_report_number_generation.py
tests/unit/test_serializer.py
tests/unit/test_video.py
tests/unit/test_webhook_receivers.py
tests/unit/test_webhook_views.py

* Configures THEOplayer to work with the Wowza server. (closes #529)
* Test refactoring.

previewer: Wowza configuration

---

cds/modules/deposit/api.py

deposit: session commit removal

---

cds/config.py
cds/modules/deposit/facets.py
cds/modules/deposit/static/templates/cds_deposit/search/facets.html
cds/modules/deposit/static/templates/cds_deposit/search/results.html
cds/modules/deposit/templates/cds_deposit/index.html
cds/modules/theme/static/scss/cds.scss

* Fixes the facets on project deposits. (closes #531)

config: addition of deposit project facets

---

cds/config.py
cds/modules/deposit/api.py
cds/modules/deposit/ext.py
cds/modules/deposit/receivers.py
cds/modules/deposit/tasks.py
cds/modules/records/mappings/records/project-v1.0.0.json
cds/modules/records/mappings/records/video-v1.0.0.json
cds/modules/records/minters.py
cds/modules/records/serializers/schemas/doi.py
cds/modules/records/serializers/schemas/project.py
cds/modules/records/serializers/schemas/video.py
cds/modules/records/static/templates/cds_records/detail.default.html
cds/modules/records/static/templates/cds_records/doi.html
cds/modules/records/static/templates/cds_records/video/detail.html
cds/modules/records/templates/cds_records/record_detail.html
cds/modules/theme/static/scss/spacing.scss
setup.py
tests/unit/conftest.py
tests/unit/test_fixtures.py
tests/unit/test_project.py
tests/unit/test_provider.py
tests/unit/test_video_rest.py

deposit: register datacite on publish

---

cds/modules/deposit/api.py
cds/modules/deposit/bundles.py
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js
cds/modules/deposit/static/templates/cds_deposit/types/common/uploader.html
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html
cds/modules/deposit/templates/cds_deposit/edit.html

* Adds progress on the extracted subformat files. (closes #539, #537)
* Adds info button with details how to delete the video.
* Fixes progress key on dumps a file. (closes #579)

deposit: add progress to extracted subformats

---

cds/config.py
cds/modules/deposit/api.py
cds/modules/deposit/receivers.py
cds/modules/fixtures/cli.py
cds/modules/fixtures/data/keywords.json
cds/modules/records/api.py
cds/modules/records/mappings/keywords/keyword-v1.0.0.json
cds/modules/records/minters.py
setup.py
tests/unit/conftest.py
tests/unit/helpers.py
tests/unit/test_deposit.py
tests/unit/test_fixtures.py
tests/unit/test_keyword.py

records: keywords addition

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js
cds/modules/deposit/static/js/cds_deposit/avc/filters/progressIcon.js
cds/modules/deposit/templates/cds_deposit/index.html
cds/modules/search_ui/static/templates/cds_search_ui/facets.html
cds/modules/search_ui/templates/cds_search_ui/search.html
cds/modules/theme/bundles.py
cds/modules/theme/static/js/cds/module.js
cds/modules/theme/static/js/main.js
cds/modules/theme/static/scss/cds.scss
cds/modules/theme/static/scss/variables.scss
cds/modules/theme/static/templates/cds/video/small.html
cds/modules/theme/templates/cds_theme/footer.html
cds/modules/theme/templates/cds_theme/header.html
cds/modules/theme/templates/cds_theme/page.html

theme: better navigation bar and flex container

---

cds/config.py
cds/modules/records/fetchers.py
cds/modules/records/search.py
tests/data/test_videos_projects.json
tests/unit/conftest.py
tests/unit/helpers.py
tests/unit/test_records.py

records: limit search results to videos

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js

* Display the preview of the first available subformat instead of the
master file. (closes #541)

deposit: first subformat preview

---

.travis.yml

This reverts commit fd6d6a19284e284b01ddc48a25b50c5151f7c76c.

Revert "travis: pin requirements-builder version"

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js
cds/modules/deposit/static/templates/cds_deposit/deposits.html
cds/modules/deposit/static/templates/cds_deposit/types/common/uploader.html

* Show error message when user tries to upload files that have the same
key as an existing file. (addresses #564)

deposit: error message on duplicate files

---

cds/modules/webhooks/receivers.py
cds/modules/webhooks/status.py
cds/modules/webhooks/views.py
tests/unit/helpers.py
tests/unit/test_webhook_receivers.py
tests/unit/test_webhook_views.py

webhooks: task info endpoint addition

---

cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js
cds/modules/deposit/static/json/cds_deposit/forms/project.json
cds/modules/deposit/static/json/cds_deposit/forms/video.json
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/uiselect.html
cds/modules/deposit/static/templates/cds_deposit/datepicker.html

* Autocomplete and suggestions for authors using the WebSubmit endpoint.
(closes #426)

deposit: author autocomplete

---

cds/modules/deposit/templates/cds_deposit/index.html

deposit: fix of bootstrap dropdowns

---

cds/config.py
cds/modules/fixtures/cli.py
cds/modules/fixtures/data/keywords.json
cds/modules/records/api.py
cds/modules/records/search.py
cds/modules/records/tasks.py
tests/unit/conftest.py
tests/unit/helpers.py
tests/unit/test_fixtures.py
tests/unit/test_keyword.py
tests/unit/test_record_tasks.py

records: task to update keywords addition

---

cds/modules/deposit/bundles.py
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js
cds/modules/deposit/static/js/cds_deposit/avc/filters/mergeObjects.js
cds/modules/deposit/static/json/cds_deposit/forms/project.json
cds/modules/deposit/static/json/cds_deposit/forms/video.json
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/uiselect.html

* Send the full info of autocompleted contributors as values instead of
only the name.

deposit: full autocompleted contributor info

---

cds/config.py
cds/modules/deposit/facets.py
cds/modules/deposit/search.py
cds/modules/deposit/static/templates/cds_deposit/search/facets.html
tests/unit/test_access_search.py
tests/unit/test_deposit_search.py

* Displays only my deposits avoiding confusion not displaying the ids of
the shared deposits.

facets: fix created by facet

---

cds/modules/deposit/static/json/cds_deposit/forms/project.json
cds/modules/records/serializers/schemas/common.py

* Closes #574.
* Requires https://github.com/CERNDocumentServer/cds-dojson/pull/55

deposit: schema form fix for _access

---

tests/unit/test_celery.py
tests/unit/test_ffmpeg.py

tests: fix celery tests and python3 compatibility

---

cds/modules/deposit/static/templates/cds_deposit/search/results.html
cds/modules/theme/static/scss/cds.scss

deposit: fix search list messages and layout

---

cds/config.py
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/uiselectmultiple.html

* Adds the template for ``uimultiselect``. (closes #615)

deposit: addition of multiple select

---

cds/config.py
cds/modules/deposit/api.py
cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js
cds/modules/deposit/static/json/cds_deposit/forms/project.json
cds/modules/deposit/static/json/cds_deposit/forms/video.json
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/uiselect.html
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/uiselectmultiple.html
cds/modules/deposit/static/templates/cds_deposit/types/common/uploader.html
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html
cds/modules/fixtures/cli.py
cds/modules/fixtures/data/licenses.json
requirements.devel.txt
setup.py
tests/unit/conftest.py
tests/unit/test_fixtures.py
tests/unit/test_project.py
tests/unit/test_project_rest.py

* Adds buttons for restarting all failed transcodings and metadata
extraction. (references #337)
* Adds an action to the subformats list to restart each individual
failed transcoding.

[WIP] deposit: failed task restart button

---

cds/config.py
cds/modules/deposit/api.py
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js
cds/modules/deposit/static/json/cds_deposit/forms/project.json
cds/modules/deposit/static/json/cds_deposit/forms/video.json
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/uiselect.html
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/uiselectmultiple.html
cds/modules/fixtures/cli.py
cds/modules/fixtures/data/licenses.json
requirements.devel.txt
setup.py
tests/unit/conftest.py
tests/unit/test_fixtures.py
tests/unit/test_project.py

* Adds fixtures for licenses.
* Configure suggester and Angular Schema Forms for project and
video. (closes #427)

deposit: license field autocompletion addition

---

requirements.devel.txt

installation: use invenio-sse master branch

---

cds/modules/records/templates/cds_records/video.smil

serializers: smil template update

---

cds/config.py
cds/modules/deposit/static/templates/cds_deposit/search/results.html
cds/modules/records/static/templates/cds_records/doi.html
cds/modules/records/static/templates/cds_records/report_number.html
cds/modules/records/static/templates/cds_records/video/detail.html

* Adds report number as a badge.
* Fixes the placeholder for projects in the deposit list. (closes #648)

global: addition of report number as a badge

---

cds/modules/deposit/static/templates/cds_deposit/search/results.html

* Fixes issues with mismatched media type. (closes #645)

deposit: fix publish of a project

---

cds/config.py
cds/modules/records/static/templates/cds_records/video/share.html
cds/modules/theme/static/js/cds/module.js

records: correct embed previewer link

---

cds/modules/deposit/static/templates/cds_deposit/types/video/form.html
cds/modules/records/static/templates/cds_records/video/downloads.html

deposit: fix loading bar

---

cds/modules/deposit/static/templates/cds_deposit/types/video/form.html
cds/modules/previewer/templates/cds_previewer/deposit_video.html
cds/modules/records/static/templates/cds_records/video/share.html

deposit: allow fullscreen on deposit

---

cds/modules/deposit/api.py
cds/modules/deposit/loaders/loader.py
tests/unit/test_video_rest.py

deposit: DOI context on marshmallow loader

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js

deposit: fix pending bar

---

cds/config.py
cds/modules/records/permissions.py
scripts/setup-instance.sh
tests/unit/conftest.py
tests/unit/helpers.py
tests/unit/test_access_search.py
tests/unit/test_deposit.py
tests/unit/test_deposit_search.py
tests/unit/test_previewer.py
tests/unit/test_project.py
tests/unit/test_project_rest.py
tests/unit/test_records.py
tests/unit/test_report_number_generation.py
tests/unit/test_video.py
tests/unit/test_video_rest.py

deposit: update permission to admins

---

cds/modules/records/static/templates/cds_records/video/detail.html

* Fixes issue with the keyword search query. (closes #672)

record: fix keyword query

---

cds/modules/deposit/api.py
tests/unit/test_project_rest.py
tests/unit/test_video_rest.py

deposit: enrich list of preserved fields

---

requirements.devel.txt
requirements.topical.branches.txt
requirements.txt

* Adds new topical branches for pending PRs. (closes #480)

requirements: update developer requirements

---

cds/config.py
cds/modules/deposit/static/templates/cds_deposit/search/results.html
cds/modules/deposit/static/templates/cds_deposit/selectbox.html
cds/modules/deposit/templates/cds_deposit/index.html
cds/modules/records/static/templates/cds_records/video/detail.html
cds/modules/theme/static/scss/cds.scss

* Adds number of video in the search result template. (closes #689)

deposit: additions in search results template

---

cds/modules/deposit/api.py
cds/modules/records/serializers/vtt.py
tests/unit/conftest.py
tests/unit/test_serializer.py

* Fixes issue with order of VTT frame information. (closes #701)
* Updates corresponding tests.

records: VTT serializer fix

---

cds/config.py
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/templates/cds_deposit/search/results.html
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html

* Adds the option to the setting dropdown to copy only contributors.
(closes #647, #688)

deposit: addition of inherit contributors button

---

cds/modules/deposit/static/json/cds_deposit/forms/project.json
cds/modules/deposit/static/json/cds_deposit/forms/video.json

* Lower the debounce time on autocomplete fields.
(closes #679)

deposit: lower autocomplete debounce

---

cds/modules/records/static/templates/cds_records/keywords.html
cds/modules/records/static/templates/cds_records/project/detail.html
cds/modules/records/static/templates/cds_records/video/detail.html
cds/modules/records/templates/cds_records/record_detail.html
cds/modules/theme/static/scss/colors.scss
cds/modules/theme/static/scss/variables.scss

* Adds template for projects. (closes #691)

records: addition of project template

---

cds/modules/records/static/templates/cds_records/video/technical_metadata.html

* Removes internal tags from the record. (closes #668)

records: removal of internal tags

---

cds/modules/deposit/static/json/cds_deposit/forms/video.json

* Re-words the title of the checkbox for the `feature` attribute in
the video deposit form (closes #685).

deposit: re-wording of featured checkbox

---

cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js

* Adds date to the inherited properties list. (closes #735)

deposit: add date to inherited properties

---

cds/modules/records/static/templates/cds_records/report_number.html

* Fixes report number badge link. (closes #740)

templates: fix report number link

---

cds/modules/fixtures/cli.py
cds/modules/theme/static/js/cds/module.js
cds/modules/webhooks/tasks.py

* GIF frames are now properly preserved on creation from frames.

records: GIF preview fix

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/fixtures/cli.py
cds/modules/fixtures/data/test_en.vtt
cds/modules/fixtures/data/test_fr.vtt
cds/modules/previewer/api.py
cds/modules/previewer/extensions/video.py
cds/modules/previewer/templates/cds_previewer/video.html
tests/unit/test_fixtures.py

* Files with a name starting with the master video's basename are now
properly included in the corresponding video deposit.
* Detects VTT files that correspond to the video and enables them in the
player. (closes #693)

previewer: subtitle support for THEOplayer

---

cds/modules/deposit/api.py
cds/modules/deposit/jsonresolver.py
cds/modules/deposit/resolver.py
cds/modules/records/jsonresolver/keywords.py
cds/modules/records/jsonresolver/records.py
cds/modules/records/serializers/schemas/project.py
cds/modules/webhooks/tasks.py
setup.py
tests/unit/conftest.py
tests/unit/test_project.py
tests/unit/test_project_rest.py
tests/unit/test_report_number_generation.py
tests/unit/test_video.py
tests/unit/test_video_rest.py
tests/unit/test_webhook_receivers.py
tests/unit/test_webhook_views.py

* Replaces $reference with $ref. (closes #721)

deposit: reference video with $ref

---

cds/modules/records/mappings/keywords/keyword-v1.0.0.json
cds/modules/records/tasks.py
tests/unit/conftest.py
tests/unit/test_record_tasks.py

* closes #625.
Requires: https://github.com/CERNDocumentServer/cds-dojson/pull/60

tasks: add provenance to the keywords

---

cds/modules/deposit/static/json/cds_deposit/forms/project.json
cds/modules/deposit/static/json/cds_deposit/forms/video.json

deposit: removal of license_url from the form

---

cds/modules/deposit/static/templates/cds_deposit/deposits.html

deposit: fix for dropbox uploader

---

cds/modules/deposit/static/templates/cds_deposit/search/results.html
cds/modules/deposit/static/templates/cds_deposit/types/project/form.html
cds/modules/deposit/templates/cds_deposit/edit.html
cds/modules/records/static/templates/cds_records/video/detail.html
cds/modules/theme/static/js/cds/module.js

global: fix speacial and html characters

---

cds/modules/deposit/static/json/cds_deposit/forms/video.json
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html

deposit: translations tabs for each video

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js

* Use all SSE events to update the deposit state.

deposit: all SSE events

---

cds/config.py
cds/modules/deposit/templates/cds_deposit/edit.html

deposits: fix video schema

---

cds/modules/deposit/api.py
cds/modules/records/serializers/smil.py
tests/unit/test_previewer.py
tests/unit/test_video.py

deposit: fix video edit/republish

---

cds/modules/deposit/api.py

* When replacing references JSONRef creates an object with the deposit metadata and it doesn't contain the model, therefore is impossible to find the bucket using `self.id`, using the deposit metadata instead solves the issue.
* Removes unnecessary `replace_refs` function as it was a work around to the problem described in the previous point.

deposit: find bucket id inside metadata first

---

cds/modules/records/static/templates/cds_records/project/detail.html
cds/modules/theme/static/js/cds/module.js

records: fix project template

---

cds/modules/deposit/static/js/cds_deposit/avc/providers/depositActions.js

deposit: data sanitization before save

---

cds/modules/deposit/static/json/cds_deposit/forms/video.json
cds/modules/previewer/api.py
cds/modules/previewer/extensions/video.py
cds/modules/previewer/templates/cds_previewer/video.html
cds/modules/records/mappings/records/videos/video/video-v1.0.0.json
cds/modules/records/serializers/schemas/video.py
requirements.devel.txt
tests/unit/helpers.py
tests/unit/test_project_rest.py

* Adds `vr` flag on videos.
* Enables 360-video support on THEOplayer. (closes #692)

previewer: 360 THEOplayer support

---

cds/modules/records/static/templates/cds_records/keywords.html
cds/modules/records/static/templates/cds_records/video/detail.html
cds/modules/theme/static/js/cds/module.js

reocrds: video detail template

---

cds/modules/deposit/mappings/deposits/records/videos/video/video-v1.0.0.json
cds/modules/deposit/static/json/cds_deposit/forms/video.json
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html
cds/modules/records/mappings/records/videos/video/video-v1.0.0.json
cds/modules/records/serializers/schemas/common.py
cds/modules/records/serializers/schemas/video.py

Edit:
Ok, so no tests for now. It worked on my machine.
We still have to display those related links in the records at some point.

deposit: added related link field to videos

---

cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js

* View file upload progress next to the other events' progress.
(closes #606)

deposit: file upload progress

---

cds/modules/deposit/api.py
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/templates/cds_deposit/edit.html
cds/modules/fixtures/cli.py
tests/unit/test_project.py

deposit: default CERN copyright

---

cds/modules/cds_iiif/ext.py

iiif: fix cache handler config

---

cds/modules/theme/static/js/cds/module.js
cds/modules/theme/static/scss/cds.scss
cds/modules/theme/static/templates/cds/video/featured-medium.html
cds/modules/theme/static/templates/cds/video/medium.html
cds/modules/theme/static/templates/cds/video/small.html

records: fix flickering gif

---

cds/modules/deposit/api.py
cds/modules/deposit/resolver.py
tests/unit/test_project_rest.py

* Fixes the project update after a video is deleted. (closed #749)

deposit: fix update project after video deletion + fix video pids marked as deleted on project deletion

---

cds/config.py
cds/modules/deposit/api.py
cds/modules/deposit/resolver.py
cds/modules/records/links.py
cds/modules/records/resolver.py
cds/modules/records/static/templates/cds_records/video/detail.html
tests/unit/test_video_rest.py

* Adds project links inside video serialization. (closes #739)

records: project links inside video serialization

---

cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js

* Changes the required field message to a more human readable one.
(closes #785)

deposit: better required field message

---

cds/modules/deposit/static/json/cds_deposit/forms/project.json
cds/modules/deposit/static/json/cds_deposit/forms/video.json

* Change "Name" to "Title" in project and video forms. (closes #748)

deposit: title instead of name

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js
cds/modules/deposit/static/json/cds_deposit/forms/project.json
cds/modules/deposit/static/json/cds_deposit/forms/video.json
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/array.html
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/button.html
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/checkbox.html
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/ckeditor.html
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/datepicker.html
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/default.html
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/fieldset.html
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/radios.html
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/radios_inline.html
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/select.html
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/strapselect.html
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/textarea.html
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/uiselect.html
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/uiselectmultiple.html
cds/modules/deposit/static/templates/cds_deposit/types/project/actions.html
cds/modules/deposit/static/templates/cds_deposit/types/project/form.html
cds/modules/deposit/static/templates/cds_deposit/types/video/actions.html
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html

* Disables form editing when project/video has been published.
(closes #717, closes #797, closes #798, closes #799)

deposit: appropriate form on published state

---

cds/config.py
cds/modules/deposit/mappings/deposits/records/videos/project/project-v1.0.0.json
cds/modules/deposit/mappings/deposits/records/videos/video/video-v1.0.0.json
cds/modules/records/mappings/records/videos/project/project-v1.0.0.json
cds/modules/records/mappings/records/videos/video/video-v1.0.0.json
cds/modules/search_ui/static/templates/cds_search_ui/range.html
cds/modules/search_ui/templates/cds_search_ui/search.html

* Properly display the year range facet.

search: range facet fix

---

cds/modules/home/templates/cds_home/home.html
cds/modules/records/templates/cds_records/record_detail.html
cds/modules/search_ui/bundles.py
cds/modules/theme/static/js/cds/module.js

* Disables the url parameters from home and record page. (closes #789)

global: disable url parameters

---

cds/modules/webhooks/tasks.py

webhooks: improve of gif quality

---

cds/modules/records/static/templates/cds_records/video/detail.html
cds/modules/theme/static/js/cds/module.js

* Adds the filter to transform any piece of metadata that is supposed
to be a URL into an absolute URL.

records: displays related links

---

cds/modules/search_ui/bundles.py

search: bump version to 1.1.4

---

cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsActions.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/static/json/cds_deposit/forms/project.json
cds/modules/deposit/static/json/cds_deposit/forms/video.json
cds/modules/deposit/static/templates/cds_deposit/deposits.html
cds/modules/deposit/static/templates/cds_deposit/search/results.html
cds/modules/deposit/static/templates/cds_deposit/types/project/actions.html
cds/modules/deposit/static/templates/cds_deposit/types/project/form.html
cds/modules/deposit/static/templates/cds_deposit/types/video/actions.html
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html

**TODO**
1. Previewer does not display (needs some variable renaming, etc...)
2. Styling...

deposit: published views on deposit form

---

cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/uiselectmultiple.html

deposit: fix of multiple select inherit

---

cds/modules/deposit/static/templates/cds_deposit/types/video/form.html

* Removes the button from unpublished videos. (closes #830)

deposit: fix show more button on videos

---

cds/modules/ffmpeg/errors.py
cds/modules/ffmpeg/ffmpeg.py
tests/unit/test_ffmpeg.py
tests/unit/test_webhook_tasks.py

* The FFmpeg errors now include meaningful error information.
(closes #837)

ffmpeg: better error reporting

---

cds/modules/deposit/static/templates/cds_deposit/types/video/form.html

deposit: fix published video template

---

cds/config.py
tests/unit/helpers.py
tests/unit/test_project_rest.py

* Fixes default order on deposit list: newest first. (closes #844)

deposit: fix default order to newest first

---

cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/uiselectmultiple.html
cds/modules/theme/static/scss/cds.scss

* Disables keywords input if project is published. (closes #850)

deposit: disable keywords if project is published

---

cds/modules/deposit/static/js/cds_deposit/avc/factories/states.js

* Fixes the videos disappearing when publishing. (addresses #862)

deposit: disappearing videos fix

---

cds/modules/search_ui/static/templates/cds_search_ui/count.html

* Fixes string spelling on search. (closes #872)

search_ui: fix string spelling on search

---

cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/templates/cds_deposit/edit.html

deposit: additon of jwt

---

cds/modules/deposit/static/templates/cds_deposit/remote_upload.html

* Clarifies a bit more what a valid URL might look like. (closes #543)

deposit: better placeholder for URL upload

---

cds/factory.py
cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js

deposit: fix syntax bug

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js
cds/modules/deposit/static/json/cds_deposit/forms/project.json
cds/modules/deposit/static/templates/cds_deposit/types/project/form.html
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html

* Adds access rights options for the record.

deposit: addition of access rights for the record

---

cds/modules/deposit/static/templates/cds_deposit/deposits.html
cds/modules/deposit/templates/cds_deposit/edit.html

* Adds the list of supported file formats in the uplaod box. (closes #564)

deposit: addition of supported file formats

---

cds/modules/deposit/static/json/cds_deposit/forms/project.json
cds/modules/deposit/static/templates/cds_deposit/types/video/actions.html

deposit: improve publish button activation, avoid redirection on get categories

---

cds/modules/deposit/mappings/deposits/records/videos/project/project-v1.0.0.json
tests/unit/test_project_rest.py

* Adds _updated field inside elasticsearch mapping. (closes #885)

deposit: _updated field addition on mapping

---

cds/modules/deposit/bundles.py
cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js
cds/modules/deposit/static/js/cds_deposit/avc/providers/jwt.js
cds/modules/deposit/static/templates/cds_deposit/deposits.html
cds/modules/deposit/templates/cds_deposit/edit.html

deposit: fix http error for GET requests

---

cds/modules/theme/static/scss/cds.scss

deposit: fix height of uimultiselect

---

cds/modules/deposit/static/templates/cds_deposit/types/common/uploader.html
cds/modules/records/serializers/smil.py
cds/modules/records/static/templates/cds_records/video/detail.html
cds/modules/webhooks/tasks.py
tests/unit/helpers.py
tests/unit/test_previewer.py
tests/unit/test_webhook_receivers.py
tests/unit/test_webhook_tasks.py
tests/unit/test_webhook_views.py

* Does not add the file to the SMIL if the 'smil' is set to False.
(closes #814) (closes #871)
Co-Authored-By: Leonardo Rossi <leonardo.r@cern.ch>

tasks: adds support for smil option

---

tests/unit/conftest.py
tests/unit/test_previewer.py

tests: remove creator from fixtures, improve smil test

---

cds/modules/deposit/static/templates/cds_deposit/types/project/actions.html
cds/modules/records/mappings/records/videos/video/video-v1.0.0.json
tests/unit/conftest.py
tests/unit/test_previewer.py
tests/unit/test_project_rest.py

* Excludes some fields from search. (closes #558)
* Improves publish button activation.

records: exclude fields from search, improve publish button activation

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html

* Upload new videos one at a time instead of all together. (closes #859)

deposit: serial video upload

---

cds/modules/deposit/api.py
tests/unit/test_project.py

* Copiea _access.update from project to video when the video is
published. (closes #889)

deposit: copy _access.update to video on publish

---

cds/modules/deposit/static/templates/cds_deposit/selectbox.html

* Fixes selected sort option title. (closes #893)

deposit: fix selectbox template

---

cds/modules/deposit/mappings/deposits/records/videos/project/project-v1.0.0.json
cds/modules/deposit/mappings/deposits/records/videos/video/video-v1.0.0.json
cds/modules/records/mappings/records/videos/project/project-v1.0.0.json
cds/modules/records/mappings/records/videos/video/video-v1.0.0.json
cds/modules/records/serializers/schemas/common.py
cds/modules/records/serializers/schemas/project.py
cds/modules/records/serializers/schemas/video.py
tests/unit/conftest.py

schema: remove creator field

---

cds/modules/deposit/static/templates/cds_deposit/types/project/form.html
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html

* Show an error indicator on deposit tabs that have an error.
(closes #907)

deposit: error indicators on tabs

---

cds/config.py
cds/modules/deposit/api.py
cds/modules/deposit/mappings/deposits/records/videos/project/project-v1.0.0.json
cds/modules/webhooks/status.py
tests/unit/test_project.py
tests/unit/test_project_rest.py
tests/unit/test_video.py
tests/unit/test_webhook_status.py

* Fixes project status computation when video is deleted.
(closes #910)
* Adds title order asc/desc on deposit list page. (closes #845)

deposit: fix project status computation, title order addition

---

cds/config.py
cds/modules/deposit/facets.py
tests/unit/test_project_rest.py

* Fixes category facet.
* Uses facets filters as normal filters instead of
post_filter. (closes #712)

deposit: update facets on filtering

---

cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js
cds/modules/deposit/static/json/cds_deposit/forms/project.json
cds/modules/deposit/static/json/cds_deposit/forms/video.json
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/uiselect.html
cds/modules/deposit/static/templates/cds_deposit/deposits.html
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html
cds/modules/deposit/templates/cds_deposit/edit.html

* Fixes empty files and videos objects. (closes #914)

deposit: improve fixes empty objects

---

cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js
cds/modules/deposit/static/templates/cds_deposit/types/project/form.html
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html

* Adds email suggestions for record restrictions.
* Fixes record restrictions disappearing when refreshing a deposit.
(closes #905)

deposit: record restriction improvements

---

cds/modules/deposit/static/js/cds_deposit/avc/providers/depositActions.js
cds/modules/deposit/static/templates/cds_deposit/types/video/actions.html

* Changes partial save to normal on publish.
* Removes empty arrays when sanitizing data.

deposit: normal save instead of partial when publishing

---

cds/modules/deposit/static/templates/cds_deposit/search/results.html
cds/modules/deposit/static/templates/cds_deposit/types/project/form.html
cds/modules/theme/static/js/cds/module.js

* Fixes the length of the project description. (closes #939)

deposit: fix length of project description

---

cds/config.py
cds/modules/records/templates/cds_records/record_detail.html

* Updates related records query. (closes #924)

records: update related records query

---

cds/modules/records/serializers/drupal.py
cds/modules/records/templates/cds_records/record_detail.html

* Adds opengraph metadata inside record details. (closes #834)

records: opengraph metadata addition, fix drupal thumbnail serializer

---

cds/modules/deposit/mappings/deposits/records/videos/video/video-v1.0.0.json
cds/modules/records/mappings/records/videos/video/video-v1.0.0.json
cds/modules/records/static/templates/cds_records/video/detail.html
cds/modules/theme/static/js/cds/module.js

* Adds a flag to show if the video is restricted. (closes #935)

records: flag restricted addition on video detail, _project_id mapping addition

---

cds/modules/deposit/api.py
cds/modules/records/serializers/schemas/project.py
cds/modules/records/serializers/schemas/video.py
cds/modules/records/validators.py
cds/modules/webhooks/tasks.py
tests/unit/helpers.py
tests/unit/test_webhook_tasks.py

records: addition of fields in partial validation

---

cds/modules/theme/templates/cds_theme/_macros.html
cds/modules/theme/templates/cds_theme/login_user.html
setup.py

* Set correct next URL parameter to the login link so the redirect after the login works properly.

login: fix login redirect

---

cds/config.py
cds/modules/deposit/api.py
cds/modules/records/links.py
cds/modules/records/static/templates/cds_records/project/detail.html
cds/modules/records/static/templates/cds_records/video/detail.html
tests/unit/test_project_rest.py
tests/unit/test_video_rest.py

* Adds a edit link on record video and project page.
(closes #911)

records: show edit link on record video, project

---

cds/config.py

* Changes the URL of the streaming server, from ``cdseos`` to ``cds``.

config: update of streaming server

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js

* Fixes display issue for authors coming from custom sources as they only have `name` field.

desposit: fix author autocmp for custom authors

---

cds/modules/records/static/templates/cds_records/video/share.html

* Adds linkedin button. (closes #960)
* Fixes the share title and urls.

records: addition of linkedin button

---

cds/modules/deposit/bundles.py
cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js
cds/modules/deposit/static/js/cds_deposit/avc/filters/overallState.js
cds/modules/deposit/static/js/cds_deposit/avc/providers/depositActions.js
cds/modules/deposit/static/json/cds_deposit/forms/project.json
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/uiselectmultiple.html
cds/modules/deposit/static/templates/cds_deposit/types/project/form.html
cds/modules/theme/bundles.py

* Adds autocomplete to share a deposit. (closes #938)
* Removes ``underscore`` in favor of ``lodash``.

deposit: addition of autocomplete to share deposit

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js
cds/modules/deposit/static/templates/cds_deposit/types/common/uploader.html

* Replace the master video file of a deposit by uploading another video.
(references #951)

deposit: replace master video file

---

cds/modules/deposit/api.py
cds/modules/previewer/api.py
cds/modules/previewer/templates/cds_previewer/deposit_video.html

* Displays the subtitles in the deposit's previewer. (closes #953)

deposit: subtitles in previewer

---

cds/modules/deposit/api.py
tests/data/test_videos_projects.json
tests/unit/test_records.py

deposit: fix duration field

---

cds/modules/webhooks/tasks.py
tests/unit/helpers.py
tests/unit/test_webhook_receivers.py
tests/unit/test_webhook_views.py

* Adds all available tags from the preset into the object version.

webhooks: addition of all preset tags

---

cds/modules/deposit/api.py
cds/modules/deposit/static/templates/cds_deposit/types/project/actions.html
cds/modules/deposit/static/templates/cds_deposit/types/video/actions.html
cds/modules/webhooks/receivers.py
cds/modules/webhooks/status.py
cds/modules/webhooks/tasks.py
tests/unit/test_project.py
tests/unit/test_webhook_receivers.py
tests/unit/test_webhook_status.py
tests/unit/test_webhook_views.py

* Modifies the publish workflow to be able to publish video also
when the workflow is still going. (closes #954)
*  Moves clean call inside celery task when restart.
when the workflow is still going. (closes #954)

deposit: publish with not all video transcoded, clean inside celery task when restart

---

cds/config.py
cds/modules/previewer/templates/cds_previewer/video.html
cds/modules/records/static/templates/cds_records/video/detail.html
cds/modules/records/static/templates/cds_records/video/downloads.html
cds/modules/records/static/templates/cds_records/video/share.html
cds/modules/records/static/templates/cds_records/video/technical_metadata.html
cds/modules/theme/static/scss/colors.scss
cds/modules/theme/static/scss/spacing.scss
tests/unit/conftest.py
tests/unit/test_previewer.py

* Adds duration in the detail view. (closes #948)
* Improves the description section.
* Improves files download list.
* Fallback to HTML video player if ``THEO_LICENCE_KEY`` is not set.

records: improve of detail view

---

cds/modules/deposit/api.py
cds/modules/deposit/static/templates/cds_deposit/types/video/actions.html
cds/modules/webhooks/tasks.py

* aligns deposit and record revisions.
* Adds force publish button.

deposit: align deposit and record revisions, force publish button addition

---

cds/modules/fixtures/data/videos/ATLAS-VIDEO-2017-013.json
cds/modules/records/static/templates/cds_records/video/downloads.html
cds/modules/theme/static/js/cds/module.js

records: addition of sections in downloads

---

cds/config.py
cds/modules/deposit/api.py
cds/modules/deposit/indexer.py
cds/modules/deposit/mappings/deposits/records/videos/project/project-v1.0.0.json
cds/modules/deposit/mappings/deposits/records/videos/video/video-v1.0.0.json
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js
cds/modules/deposit/static/templates/cds_deposit/search/results.html
cds/modules/deposit/tasks.py
cds/modules/records/mappings/records/videos/project/project-v1.0.0.json
cds/modules/records/mappings/records/videos/video/video-v1.0.0.json
cds/modules/records/serializers/schemas/project.py
cds/modules/records/serializers/schemas/video.py
cds/modules/webhooks/tasks.py
requirements.devel.txt
tests/unit/conftest.py
tests/unit/helpers.py
tests/unit/test_project.py
tests/unit/test_video.py
tests/unit/test_webhook_receivers.py
tests/unit/test_webhook_tasks.py
tests/unit/test_webhook_views.py

global: move metadata and state out of _deposit

---

cds/modules/deposit/static/js/cds_deposit/avc/factories/states.js

deposit: fix cache issues

---

cds/modules/fixtures/data/videos/ATLAS-VIDEO-2017-013.json
cds/modules/records/static/templates/cds_records/video/detail.html
cds/modules/records/static/templates/cds_records/video/downloads.html
cds/modules/theme/static/js/cds/module.js

* Improves the download file list. It separated the subformats for download
with the additional file formats.

record: better download file list

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js

* Fixes the uploader issue which didn't upload more than one video.

deposit: fix uploader for video files

---

cds/modules/records/serializers/smil.py
tests/unit/conftest.py
tests/unit/helpers.py
tests/unit/test_previewer.py
tests/unit/test_webhook_receivers.py
tests/unit/test_webhook_tasks.py
tests/unit/test_webhook_views.py

serializers: fix smil file

---

cds/config.py
cds/modules/deposit/bundles.py
cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/providers/depositExtractedMetadata.js
cds/modules/ffmpeg/ffmpeg.py
cds/modules/webhooks/tasks.py
tests/unit/conftest.py
tests/unit/test_ffmpeg.py

deposit: fill form with extracted video metadata

---

cds/modules/deposit/bundles.py
cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js
cds/modules/deposit/static/js/cds_deposit/avc/filters/overallState.js
cds/modules/deposit/static/js/cds_deposit/avc/filters/progressClass.js
cds/modules/deposit/static/js/cds_deposit/avc/filters/progressIcon.js
cds/modules/deposit/static/json/cds_deposit/forms/project.json
cds/modules/deposit/static/json/cds_deposit/forms/video.json
cds/modules/deposit/static/templates/cds_deposit/deposits.html
cds/modules/deposit/static/templates/cds_deposit/search/results.html
cds/modules/deposit/static/templates/cds_deposit/types/common/uploader.html
cds/modules/deposit/static/templates/cds_deposit/types/project/form.html
cds/modules/deposit/static/templates/cds_deposit/types/video/actions.html
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html
cds/modules/deposit/templates/cds_deposit/edit.html
cds/modules/deposit/templates/cds_deposit/index.html
cds/modules/theme/bundles.py
cds/modules/theme/static/scss/cds.scss
cds/modules/theme/static/scss/colors.scss
cds/modules/theme/templates/cds_theme/header.html

* Changes the title from ``video`` to ``videos``. (closes #686)
* Improves the overall UX of the deposit.

deposit: change deposit layout

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js
cds/modules/deposit/static/templates/cds_deposit/deposits.html
cds/modules/deposit/static/templates/cds_deposit/list.html
cds/modules/deposit/static/templates/cds_deposit/types/common/uploader.html
cds/modules/deposit/static/templates/cds_deposit/types/video/uploader.html
cds/modules/theme/static/js/cds/module.js
cds/modules/theme/static/scss/cds.scss

deposit: addition of sections in uploader

---

cds/modules/deposit/static/templates/cds_deposit/types/video/form.html

* Adds record url on the published video view. (closes #998)

deposit: fix of published view for videos

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js
cds/modules/deposit/static/templates/cds_deposit/types/project/form.html
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html

* Improves the autocompletion for users. (closes #1005)

deposit: improve of name autocompletion

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsActions.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/templates/cds_deposit/types/project/actions.html
cds/modules/deposit/static/templates/cds_deposit/types/video/actions.html

* Adds a success message when the metadata are saved. (closes #1006)

deposit: addition of auto-fill success message

---

cds/modules/theme/templates/cds_theme/login_user.html
cds/modules/theme/templates/cds_theme/page_cover.html

* Fixes issue with missplaced flash messages. (closes #1003)

access: fix of wrong placed flash messages

---

cds/modules/records/serializers/schemas/project.py
tests/unit/test_deposit_validation.py

records: date field not required from project

---

cds/config.py
cds/modules/previewer/api.py
cds/modules/previewer/extensions/video.py
cds/modules/previewer/templates/cds_previewer/base.html
cds/modules/previewer/templates/cds_previewer/deposit_video.html
cds/modules/previewer/templates/cds_previewer/embedded_video.html
cds/modules/previewer/templates/cds_previewer/video.html
tests/unit/test_previewer.py

previewer: addition of THEOPlayer v2

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html

deposit: fix error message on delete

---

cds/modules/deposit/api.py
cds/modules/deposit/mappings/deposits/records/videos/project/project-v1.0.0.json
cds/modules/deposit/mappings/deposits/records/videos/video/video-v1.0.0.json
cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js
cds/modules/deposit/static/json/cds_deposit/forms/project.json
cds/modules/deposit/static/json/cds_deposit/forms/video.json
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/array.html
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/uiselect.html
cds/modules/deposit/static/templates/cds_deposit/deposits.html
cds/modules/deposit/static/templates/cds_deposit/search/results.html
cds/modules/records/mappings/records/videos/project/project-v1.0.0.json
cds/modules/records/mappings/records/videos/video/video-v1.0.0.json
cds/modules/records/serializers/schemas/common.py
cds/modules/records/static/templates/cds_records/video/detail.html
cds/modules/records/static/templates/cds_records/video/downloads.html
cds/modules/theme/static/js/cds/module.js
cds/modules/theme/static/js/main.js
cds/modules/theme/static/scss/cds.scss
cds/modules/theme/static/scss/colors.scss

* Adds licenses with credits to the UI. (closes #1001)

global: addition of licenses

---

tests/unit/helpers.py
tests/unit/test_video.py

tests: update oauth2 requests

---

cds/modules/fixtures/data/videos/ATLAS-VIDEO-2017-013.json

* Fixes record metadata to pass current validation.
(closes #1069)

fixtures: update records load

---

cds/config.py
cds/modules/home/templates/cds_home/home.html
cds/modules/records/static/templates/cds_records/keywords.html

Added search query to channels and changed them to dynamic configuration

---

cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js
cds/modules/records/bundles.py
cds/modules/records/static/js/cds_records/main.js

- Fixed author name lost when changing role or custom author name
- Fixed unsafe warning on record details page
- closes #1065

global: contributors field and unsafe HTML fixes

---

cds/modules/fixtures/video_utils.py
cds/modules/webhooks/tasks.py
tests/unit/helpers.py
tests/unit/test_ffmpeg.py
tests/unit/test_webhook_receivers.py
tests/unit/test_webhook_tasks.py

* Added the metadata codec_long_name to the tags object (closes #986)

global: added codec_long_name to file tags

---

cds/modules/fixtures/data/pages/about.html
cds/modules/fixtures/data/pages/contact.html
cds/modules/fixtures/data/pages/feedback.html
cds/modules/fixtures/data/pages/help.html
cds/modules/fixtures/data/pages/terms_of_use.html

First version of static pages for production

Update static pages

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/json/cds_deposit/forms/project.json
cds/modules/deposit/static/json/cds_deposit/forms/video.json
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/datepicker.html

* Fixes validation for datepicker field. (closes #1029)
* Updates the contributors roles.

deposit: fix datepicker validation

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsActions.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js
cds/modules/deposit/static/js/cds_deposit/avc/factories/states.js
cds/modules/deposit/static/templates/cds_deposit/types/project/actions.html

* Changed upload form behaviour to save project and videos details
when clicking on Save All button (closes #979)

global: upload form saves project and videos

---

cds/modules/deposit/api.py
cds/modules/deposit/tasks.py
cds/modules/records/minters.py
tests/unit/test_provider.py

* Skips minting DOI for projects (closes #996).

records: no DOI minting for Project

---

cds/modules/deposit/api.py
cds/modules/migrator/records.py

* Fixes project resolve on video migration. (closes #1057)
* In case the video doesn't specify any contributors, inherit them
from the project. (closes #1077)

migration pack #1

---

cds/modules/deposit/api.py
tests/unit/conftest.py
tests/unit/test_deposit.py
tests/unit/test_migration.py
tests/unit/test_previewer.py
tests/unit/test_project.py
tests/unit/test_project_rest.py
tests/unit/test_report_number_generation.py
tests/unit/test_video.py
tests/unit/test_webhook_tasks.py

* Adds modified_by field on deposit publish. (closes #991)

deposit: add modified_by on publish

---

cds/modules/theme/static/js/cds/module.js

theme: fix isPublic filter

---

cds/config.py
cds/modules/previewer/extensions/video.py
cds/modules/previewer/templates/cds_previewer/deposit_video.html
cds/modules/previewer/templates/cds_previewer/video.html
cds/modules/records/api.py
cds/modules/records/bundles.py
cds/modules/records/static/js/cds_records/user_actions_logger.js
cds/modules/records/static/templates/cds_records/video/downloads.html
cds/modules/records/templates/cds_records/record_detail.html
tests/unit/test_project_rest.py

* Send an async request when the user clicks on Play on the video
player to log the event.
* Feature disabled for deposit video preview.

global: log media view event.

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js
cds/modules/deposit/static/templates/cds_deposit/types/video/uploader.html

* Adds an incremental indicator for how many times a master video file
has been replaced by adding ``times_replaced`` object version tag.
(closes #1032)

deposit: addition of master file indicator

---

cds/modules/records/static/templates/cds_records/video/detail.html

* Adds license notice for unknown licenses.
* Removes license title when there is only one.

records: addition of unknown license modal

---

cds/modules/deposit/static/templates/cds_deposit/types/video/form.html
cds/modules/theme/bundles.py
cds/modules/theme/static/js/cds/module.js

* Fixes issue with inherit button dropdown menu. (closes #1114)

deposit: fix dropdown menu

---

cds/modules/cds_iiif/utils.py
cds/modules/webhooks/tasks.py
cds/modules/xrootd/utils.py

* Changes the IIIF file opener. (closes #1109)

cds_iiif: enable XrootD opener for IIIF

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/uiselect.html

fix contributors inherit

---

cds/modules/xrootd/utils.py

xrootd: fix file path

---

cds/modules/migrator/records.py
cds/modules/records/symlinks.py
tests/unit/test_migration.py

migrator: create symlinks on migration

---

cds/modules/migrator/records.py

migrator: open bucket on gif creation

---

cds/config.py
cds/modules/records/static/templates/cds_records/project/detail.html
cds/modules/records/static/templates/cds_records/video/detail.html
cds/modules/search_ui/static/templates/cds_search_ui/facets.html
cds/modules/theme/static/js/cds/module.js
cds/modules/theme/static/scss/cds.scss
cds/modules/theme/static/templates/cds/video/featured-medium.html
cds/modules/theme/static/templates/cds/video/medium.html
cds/modules/theme/static/templates/cds/video/small.html

* Improves the ``edit`` button.
* Adds language names instead of ISO code.
* Fixes the tranlation title template.

records: improvment of the interface

---

cds/modules/records/serializers/schemas/video.py

serializers: add missing fields after migration

---

cds/modules/search_ui/bundles.py
cds/modules/search_ui/static/templates/cds_search_ui/range.html
cds/modules/search_ui/templates/cds_search_ui/search.html

* Improves the year range facet filter by increasing the size, adding
a small bar when the year is empty and on hover changes the color
and the cursor. (closes #1137)

search: improvements of year range facet filter

---

cds/config.py
cds/modules/deposit/facets.py

config: set dynamic facets for records

---

cds/modules/records/static/templates/cds_records/report_number.html

templates: fix report number badge URL

---

cds/modules/records/static/templates/cds_records/project/detail.html

* Remove ``uploaded on`` from the project template. (closes #1168)

records: removal of uploaded date

---

cds/modules/deposit/static/json/cds_deposit/forms/video.json

* Adds ``Silent`` in the list of languages. (closes ##1166)

deposit: addition of ``Silent`` in languages

---

cds/modules/search_ui/static/templates/cds_search_ui/count.html
cds/modules/search_ui/static/templates/cds_search_ui/range.html
cds/modules/theme/static/js/cds/module.js

* Improves the search results empty message by adding all the selected
facets in the message. (closes #1153)

search: improvement of search results

---

cds/modules/search_ui/static/templates/cds_search_ui/pagination.html

* Hides the Next/Previous buttons from the UI. (closes #1154)

search: hide the Next/Previous buttons

---

cds/modules/records/static/templates/cds_records/report_number.html
cds/modules/records/static/templates/cds_records/video/detail.html
cds/modules/theme/static/js/cds/module.js

* Adds click to copy on the report number. (closes #1170)

records: addition of click to copy

---

cds/modules/deposit/templates/cds_deposit/edit.html
cds/modules/deposit/templates/cds_deposit/index.html
cds/modules/records/templates/cds_records/record_detail.html
cds/modules/search_ui/templates/cds_search_ui/search.html
cds/modules/theme/templates/cds_theme/login_user.html
cds/modules/theme/templates/cds_theme/page.html

* Fixes duplicate title on the pages. (closes #1158)

global: fix of title

---

cds/modules/deposit/bundles.py
cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsActions.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/templates/cds_deposit/types/project/actions.html
cds/modules/deposit/static/templates/cds_deposit/types/video/actions.html

* Reduces the notification message only to imporant events and adds
load indication bar. (closes #1163)

deposit: fix of alert messages

---

cds/config.py
cds/modules/migrator/records.py
tests/unit/test_migration.py

* remove date from projects
* run symlink creation as celery task

Migration fixes

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsActions.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js

deposit: fix of ``SAVE_ALL`` error

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js

* Fixes value of autocomplete for licenses. (closes #1194, #1193)

deposit: fix licenses autocomplete value

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/templates/cds_deposit/deposits.html

deposit: addition of edit link

---

cds/modules/search_ui/bundles.py
cds/modules/search_ui/static/templates/cds_search_ui/facets.html
cds/modules/search_ui/static/templates/cds_search_ui/range.html
cds/modules/theme/static/scss/decorators.scss

Need to merge first: https://github.com/inveniosoftware/invenio-search-js/pull/102
And probably update the version dependency of `invenio-search-js`?
Let me know if the `Clear` text is ok or you prefer to also add an icon:

global: added reset link on year facet

---

cds/modules/records/static/templates/cds_records/video/detail.html
cds/modules/theme/static/js/cds/module.js

* Adds all available transations in the UI. (closes #1160)

records: addition of all available translations

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js
cds/modules/deposit/static/json/cds_deposit/forms/project.json
cds/modules/deposit/static/json/cds_deposit/forms/video.json
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/array.html

* Changes the form state to ``dirty`` when someone orders the
contributors. (closes #1203)
* Disables ordering on ``licenses`` and ``translations``.

deposit: set form state to dirty on order change

---

cds/modules/records/templates/cds_records/record_detail.html
cds/modules/stats/views.py

records: fix of stat views

---

cds/modules/deposit/static/json/cds_deposit/forms/video.json

deposit: fix video form

---

cds/modules/migrator/records.py

migration: fixes

---

cds/modules/deposit/static/templates/cds_deposit/deposits.html
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html
cds/modules/deposit/templates/cds_deposit/edit.html
cds/modules/deposit/templates/cds_deposit/index.html
cds/modules/home/templates/cds_home/home.html
cds/modules/previewer/templates/cds_previewer/default.html
cds/modules/previewer/templates/cds_previewer/video.html
cds/modules/records/static/templates/cds_records/popup_template.html
cds/modules/records/static/templates/cds_records/project/detail.html
cds/modules/records/static/templates/cds_records/video/detail.html
cds/modules/records/templates/cds_records/record_detail.html
cds/modules/search_ui/templates/cds_search_ui/search.html
cds/modules/theme/bundles.py
cds/modules/theme/static/js/cds/module.js
cds/modules/theme/static/js/main.js
cds/modules/theme/static/scss/cds.scss
cds/modules/theme/static/scss/colors.scss
cds/modules/theme/static/scss/variables.scss
cds/modules/theme/static/templates/cds/video/featured.html
cds/modules/theme/templates/cds_theme/error/404.html
cds/modules/theme/templates/cds_theme/error/500.html
cds/modules/theme/templates/cds_theme/footer.html
cds/modules/theme/templates/cds_theme/header.html
cds/modules/theme/templates/cds_theme/login_user.html
cds/modules/theme/templates/cds_theme/page.html
cds/modules/theme/templates/cds_theme/page_cover.html

global: improvements of UI

---

cds/modules/migrator/records.py
tests/unit/test_migration.py

* Cleans file list before starting the migration removing all missing files.
* Adds fail safe when handling files, the tasks will log the errors instead of failing.

migrator: better file management

---

cds/modules/migrator/records.py

WIP migrator: fix not found account

---

cds/modules/migrator/cli.py
cds/modules/migrator/records.py

* Adds new command to undo a migration based on a file, same as for loadrecords, or based on a recid.

migrator: add cleanrecords command

---

cds/modules/records/static/templates/cds_records/video/detail.html

records: fix view counter issue

---

cds/modules/deposit/static/json/cds_deposit/forms/project.json
cds/modules/deposit/static/json/cds_deposit/forms/video.json
cds/modules/theme/static/js/cds/module.js

Languages service pack 1

---

cds/modules/home/templates/cds_home/home.html
cds/modules/records/static/templates/cds_records/video/detail.html
cds/modules/search_ui/static/templates/cds_search_ui/count.html
cds/modules/theme/static/templates/cds/video/featured.html

* Fixes issues with previewer 404 errors until the record is loaded.
(closes #1248)

records: fix previwer 404 errors

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html

deposit: removed inherit metadata from project

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js
cds/modules/deposit/static/templates/cds_deposit/deposits.html
cds/modules/deposit/static/templates/cds_deposit/types/video/actions.html
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html

deposit: fix brief view on publish

---

cds/modules/deposit/static/json/cds_deposit/forms/project.json
cds/modules/deposit/static/json/cds_deposit/forms/video.json
cds/modules/deposit/static/templates/cds_deposit/deposits.html
cds/modules/deposit/static/templates/cds_deposit/types/common/uploader.html
cds/modules/deposit/static/templates/cds_deposit/types/project/form.html
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html
cds/modules/deposit/static/templates/cds_deposit/types/video/uploader.html

* Fixes progress bar alignment.
* Fixes share deposit to be disabled when the project is ``published``.
* Fixes titles on Related Links and Translations.
* Disables upload on subtitles when the status is ``published``.
* Adds a message to ``Files`` tab when the status is ``published``.

deposit: fix UI details

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/uiselect.html
cds/modules/deposit/static/templates/cds_deposit/types/project/actions.html
cds/modules/deposit/static/templates/cds_deposit/types/project/form.html
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html

* Fixes basic info permanent red dot. (closes #1246)
* Changes the icon of the red dot to be more clear for the users and
includes tooltips.

deposit: improves validation red dot

---

cds/config.py
cds/modules/deposit/api.py
cds/modules/previewer/templates/cds_previewer/deposit_video.html
cds/modules/records/links.py

global: fix issues with migrated records

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsActions.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js
cds/modules/deposit/static/json/cds_deposit/forms/project.json
cds/modules/deposit/static/templates/cds_deposit/deposits.html
cds/modules/deposit/static/templates/cds_deposit/types/project/form.html
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html

* ask confirmation when at least one video is already published and the
category or type are changed.

deposit: warn on category/type change if published

---

cds/config.py
cds/modules/deposit/api.py
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js
cds/modules/deposit/static/json/cds_deposit/forms/project.json
cds/modules/deposit/templates/cds_deposit/edit.html
cds/modules/deposit/views.py
cds/modules/records/permissions.py
cds/modules/records/serializers/__init__.py
cds/modules/records/serializers/json.py
cds/modules/records/serializers/schemas/project.py
cds/modules/records/static/templates/cds_records/project/detail.html
tests/unit/test_access_records.py

* Adds the EOS path to library field, which is only visible to
admins add users that are part of ``VIDEOS_EOS_PATH_EGROUPS``.
(closes #1257)

global: addition of EOS path

---

cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/uiselectmultiple.html
cds/modules/deposit/static/templates/cds_deposit/deposits.html
cds/modules/deposit/static/templates/cds_deposit/types/common/custom_authors_dialog.html
cds/modules/deposit/static/templates/cds_deposit/types/common/uploader.html
cds/modules/deposit/static/templates/cds_deposit/types/project/form.html
cds/modules/deposit/static/templates/cds_deposit/types/video/action_delete.html
cds/modules/deposit/static/templates/cds_deposit/types/video/actions.html
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html
cds/modules/deposit/static/templates/cds_deposit/types/video/uploader.html
cds/modules/deposit/templates/cds_deposit/index.html
cds/modules/records/static/templates/cds_records/video/detail.html
cds/modules/records/static/templates/cds_records/video/downloads.html
cds/modules/theme/static/scss/cds.scss

* Fixes multiselect field to tokenize the tags. (closes #1250)
* Relocates the project's action buttons.
* Adds better messages to modals.

deposit: improvement of multiselect field

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsActions.js
cds/modules/deposit/static/templates/cds_deposit/types/project/actions.html
cds/modules/deposit/static/templates/cds_deposit/types/video/actions.html
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html

deposit: publish project saves videos first

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js
cds/modules/deposit/static/json/cds_deposit/forms/project.json
cds/modules/deposit/static/json/cds_deposit/forms/video.json
cds/modules/deposit/static/templates/cds_deposit/types/project/form.html
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html
cds/modules/deposit/templates/cds_deposit/edit.html
cds/modules/deposit/templates/cds_deposit/index.html
cds/modules/deposit/views.py

deposit: move record restrictions

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js

deposit: show task success only when not publshed

---

cds/config.py
cds/modules/webhooks/tasks.py
cds/modules/webhooks/utils.py
tests/unit/conftest.py
tests/unit/test_webhook_tasks.py

* Adds the contex manager ``get_download_file_url`` which
generates a token with the super user and returns the
url. The token is deleted as soon as the process is finished.

webhooks: addition of file url download

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/uiselect.html

* Fixes an issue when you add and delete a contributor. (closes #1295)

deposit: fix contributors add functionality

---

cds/modules/theme/static/scss/cds.scss

global: fix loading bar z-index

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsActions.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js
cds/modules/deposit/static/templates/cds_deposit/types/project/actions.html
cds/modules/deposit/static/templates/cds_deposit/types/video/actions.html
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html
cds/modules/theme/static/scss/cds.scss

* Fixes frozen statuses my refreshing deposit ``_cds`` every 30 secs.
(closes #1285)

deposit: fix frozen statuses

---

cds/modules/deposit/api.py

* Adds the current's user email in the ``_access.update``.

deposit: addition of current user email

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/json/cds_deposit/forms/video.json
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/uiselectmultiple.html
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html

* Fixes a bug with keywords, which the changes were propagated to all
videos.

deposit: fix keywords duplication

---

cds/config.py
cds/modules/cds_iiif/utils.py
cds/modules/migrator/records.py
cds/modules/records/tasks.py
cds/modules/webhooks/tasks.py
cds/modules/webhooks/utils.py
cds/modules/xrootd/utils.py
tests/unit/conftest.py
tests/unit/test_migration.py
tests/unit/test_video_rest.py
tests/unit/test_webhook_tasks.py

* Makes use of a function that returns temporary URLs for a given object
(so we can use the XRootD for ffmpeg tasks).
* Requires #1303.

[WIP] webhooks: ffmpeg use file url download

---

cds/modules/records/templates/cds_records/record_detail.html

records: fix template type

---

cds/modules/records/serializers/schemas/common.py
cds/modules/records/serializers/schemas/project.py
cds/modules/records/serializers/schemas/video.py

schemas: addition of external_system_identifiers

---

cds/modules/migrator/records.py

* Fixes missing ``preset_quality`` tag.
* Fixes missing ``subformats`` key from the file.

migrator: fix missing ``preset_quality``

---

cds/modules/previewer/extensions/video.py

* Adds .mpg to the list of file extensions that can be previewed.

previewer: add mpg

---

cds/config.py
requirements.devel.txt
requirements.pinned.txt
setup.py

Changes as: https://github.com/zenodo/zenodo/commit/0fc186d76a38d1f578629eb1ef86a0f148c6a938

config: upgraded min version raven for Sentry

---

cds/modules/records/static/templates/cds_records/video/downloads.html

details: fixed button to download master file

---

cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js

deposit: remove cache from ``GET`` requests

---

.travis-requirements-build.sh
.travis.yml
requirements.pinned.txt
requirements.prod.txt
requirements.qa.txt

* Updates versions of pinned requirements.
* Creates 2 requirements file, one for testing machine and one for
production.

requirements: update pinned requirements

---

cds/modules/migrator/cli.py
tests/unit/test_migration.py

* Updates sequence generator CLI to also create the counter for videos within existing projects.

migrator: update sequence generator CLI

---

cds/modules/deposit/mappings/deposits/records/videos/video/video-v1.0.0.json

deposit: update video mappings

---

cds/modules/theme/static/js/cds/module.js
cds/modules/theme/static/templates/cds/video/featured-medium.html
cds/modules/theme/static/templates/cds/video/medium.html
cds/modules/theme/static/templates/cds/video/small.html

global: fix frames in the templates

---

cds/config.py
cds/modules/deposit/static/templates/cds_deposit/search/results.html
cds/modules/deposit/static/templates/cds_deposit/types/project/form.html
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html
cds/modules/records/serializers/__init__.py
cds/modules/records/serializers/drupal.py
cds/modules/records/serializers/json.py
cds/modules/records/static/templates/cds_records/video/detail.html
cds/modules/records/templates/cds_records/record_detail.html
cds/modules/records/utils.py
cds/modules/theme/static/js/cds/module.js
tests/unit/conftest.py
tests/unit/helpers.py
tests/unit/test_records.py
tests/unit/test_schema_datacite.py
tests/unit/test_serializer.py

- decode html entities from title and description
- remove html tags from title
- closes #1382

details: fixed incorrect html tags rendering

---

cds/modules/previewer/api.py
cds/modules/previewer/static/css/cds_previewer/video.css
cds/modules/previewer/templates/cds_previewer/macros/player.html
tests/unit/test_previewer.py

Co-authored-by: Nicola Tarocco <nicola.tarocco@cern.ch>

previewer: fix iframe resizing

---

cds/config.py

config: fix most recent videos query

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html
cds/modules/deposit/static/templates/cds_deposit/types/video/uploader.html
cds/modules/deposit/templates/cds_deposit/edit.html
cds/modules/deposit/views.py

deposit: addition of admin interface

---

cds/modules/theme/templates/cds_theme/page.html

global: improvement of page title

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js
cds/modules/deposit/static/templates/cds_deposit/types/video/actions.html
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html

deposit: restart the whole workflow

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js
cds/modules/deposit/static/templates/cds_deposit/types/video/uploader.html
cds/modules/previewer/api.py
cds/modules/records/static/templates/cds_records/detail.default.html
cds/modules/records/static/templates/cds_records/project/detail.html
cds/modules/records/static/templates/cds_records/video/downloads.html
cds/modules/records/static/templates/cds_records/video/technical_metadata.html
cds/modules/search_ui/static/templates/cds_search_ui/results.html
cds/modules/theme/static/js/cds/module.js
cds/modules/theme/static/templates/cds/video/featured-medium.html
cds/modules/theme/static/templates/cds/video/medium.html
cds/modules/theme/static/templates/cds/video/small.html
cds/modules/theme/templates/cds_theme/scripts.html

- strict subtitles filename check, forcing 2 letters for language and
valid ISO code.
- add ellipsis ng filter
- fixes js exception on home page when no description for a video

deposit: fixes to subtitles and angularjs

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js
cds/modules/deposit/static/templates/cds_deposit/deposits.html

* Instead of throwing an error for existing file names, the uploader
will upload the file as a new version. (closes #1457)

deposit: upload file as new version

---

cds/modules/deposit/static/templates/cds_deposit/types/project/admin_actions.html
cds/modules/deposit/static/templates/cds_deposit/types/project/form.html

* Adds an admin delete button for projects.

deposit: addition of admin delete button

---

cds/modules/home/decorators.py
cds/modules/home/views.py
requirements.pinned.txt
setup.py

* Caches the home page for 10 mins if the user is not authenticated and
if there is not any flash message. (closes #1466)

home: addition of cache for 10mins

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js

deposit: fixed keywords not saved

---

cds/modules/records/links.py
tests/unit/test_video_rest.py

* Improves the ``links_factory`` to always return a ``project_edit``
link, so the users can edit their videos.

records: improvement of ``links_factory``

---

cds/modules/previewer/templates/cds_previewer/macros/player.html
cds/modules/previewer/templates/cds_previewer/video/embed.html

Player to be deeply tested in QA

global: fixed wrong attrs for THEOPlayer

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsActions.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js
cds/modules/deposit/static/templates/cds_deposit/types/project/admin_actions.html
cds/modules/deposit/static/templates/cds_deposit/types/project/form.html

- removed duplicated instance of cdsActions.js which was implementing
saveAll listener and it was saving videos and project twice.
- closes #1429

deposit: fixed 500 when changing category/type

---

.gitignore
cds/modules/deposit/static/templates/cds_deposit/searchbar.html
cds/modules/search_ui/static/templates/cds_search_ui/searchbar.html
cds/modules/theme/static/scss/cds.scss
cds/modules/theme/templates/cds_theme/header.html

ui: Add submit button in searchbar

---

cds/modules/records/static/templates/cds_records/video/downloads.html
cds/modules/theme/static/js/cds/module.js

ui: Display resolution in master video download

---

cds/modules/theme/static/scss/cds.scss

ui: Allow hyphens in word breaks

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js

ui: Increase result limit in authors autocompletion

---

cds/config.py
cds/modules/theme/templates/cds_theme/profile.html

* Hides e-groups from profile page.
closes #1440

profile: fix template theme in profile page

---

cds/config.py

config: Add records-rest error handlers for elasticsearch

---

cds/modules/records/static/templates/cds_records/project/detail.html

ui: fix unescaped video description

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/templates/cds_deposit/types/video/actions.html

ui: disable publish button until frames ready

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsActions.js

project: fix project save

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsActions.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js
cds/modules/deposit/static/templates/cds_deposit/types/project/form.html
cds/modules/deposit/static/templates/cds_deposit/types/video/actions.html

deposit: fix deletion of video

---

cds/modules/previewer/templates/cds_previewer/video/embed.html

embeded videos: fix view tracking

---

cds/modules/migrator/records.py

We probably don't need any more this delay since we are using that code as recipe.

migrator: remove delay for missing slaves tasks

---

cds/modules/records/static/templates/cds_records/video/detail.html

ui: escape html tags on translation description

---

cds/modules/deposit/static/js/cds_deposit/avc/avc.module.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/templates/cds_deposit/angular-schema-form/uiselectmultiple.html

ui: fix keywords inheritance from project to videos

---

cds/modules/deposit/api.py
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js
cds/modules/fixtures/data/categories.json

access: enable egroup access rights for deposit

---

cds/modules/deposit/api.py
cds/modules/records/api.py
tests/unit/test_previewer.py
tests/unit/test_video.py

api: File renaming on publish

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposit.js
cds/modules/deposit/static/templates/cds_deposit/types/video/actions.html

ui: fix disable publish button

---

cds/config.py
cds/modules/records/tasks.py
cds/modules/records/utils.py
tests/unit/test_celery.py

global: checksum verification task and emails

---

.gitignore
cds/config.py
cds/modules/records/api.py
cds/modules/records/serializers/drupal.py
cds/modules/records/tasks.py
setup.py
tests/unit/test_records.py
tests/unit/test_serializer.py

[CDS-1188](https://its.cern.ch/jira/browse/CDS-1188)
Needs https://github.com/inveniosoftware/flask-celeryext/pull/31

Mediaexport: additions for the cern website

---

cds/modules/home/templates/cds_home/home.html
cds/modules/records/templates/cds_records/record_detail.html

search: disable url handler for home and record detail page

---

cds/config.py
cds/modules/deposit/templates/cds_deposit/edit.html
cds/modules/deposit/templates/cds_deposit/index.html
cds/modules/home/views.py
cds/modules/records/templates/cds_records/record_detail.html
cds/modules/records/templates/cds_records/record_stats.html
cds/modules/search_ui/templates/cds_search_ui/search.html
cds/modules/theme/templates/cds_theme/login_user.html
cds/modules/theme/templates/cds_theme/page.html
cds/modules/theme/templates/cds_theme/page_cover.html

* improved title and description for the main pages of the site

global: better site title and description

---

cds/config.py
cds/modules/records/search.py
tests/unit/conftest.py

* add `min_score` param to search request body to have back search
results more similar to the search query
* closes #1620

search: add min_score to search request

---

cds/modules/records/static/js/cds_records/main.js
cds/modules/records/static/templates/cds_records/video/downloads.html
cds/modules/theme/static/js/cds/module.js

Closes #1527
Please merge after this commit is merged:
https://github.com/inveniosoftware/invenio-files-rest/pull/177

ui: fix links downloading the files

---

cds/modules/deposit/static/templates/cds_deposit/types/video/form.html

Fix player not playing for published videos

---

cds/modules/records/templates/cds_records/record_detail.html

* turns off indexing of the record if it is a project
* (closes #1648)

records: noindex for project type of record

---

cds/modules/deposit/receivers.py
cds/modules/files/__init__.py
cds/modules/files/ext.py
cds/modules/files/receivers.py
setup.py
tests/unit/test_files_receivers.py

* add a listener to file download to change the filename key when the
file has been generated from the master file
* the filename has as prefix the master filename
* closes #1626

files: rename filename to match master on download

---

cds/modules/records/static/templates/cds_records/video/share.html
cds/modules/theme/static/js/cds/module.js

Added different formats for sharing on different
social platforms
Closes #1616

ui: fix video sharing

---

cds/modules/theme/static/js/cds/module.js

* Adds missing languages wrongly migrated as "silence"
before. (addresses #1363)

theme: add missing languages

---

cds/config.py
cds/modules/fixtures/data/categories.json
tests/unit/test_access_records.py

access: change egroups access for CERN videos

---

cds/modules/records/bundles.py
cds/modules/records/static/js/cds_records/stats.js
cds/modules/records/templates/cds_records/record_stats.html
cds/modules/records/views.py
cds/modules/stats/views.py

Also regarding this issue I made a [PR for invenio-charts-js](https://github.com/inveniosoftware/invenio-charts-js/pull/1 ).
Closes #1549 
If you are waiting for the API calls this loading will apear:
When the API calls are failing this is the message that we are showing.

ui: fix download statistics

---

cds/modules/records/static/templates/cds_records/video/detail.html

Fix: link to statistics from video views

---

cds/modules/deposit/static/templates/cds_deposit/types/project/form.html
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html

* change placeholders for access right input field (video and project)
* (closes #1639)

deposit: change placeholder for access rights

---

cds/modules/search_ui/bundles.py
cds/modules/search_ui/static/js/invenio_search_bar_suggestions.js
cds/modules/search_ui/static/templates/cds_search_ui/searchbar.html
cds/modules/search_ui/templates/cds_search_ui/header.html
cds/modules/theme/bundles.py
cds/modules/theme/static/js/cds/suggestions.js
cds/modules/theme/static/js/main.js
cds/modules/theme/templates/cds_theme/header.html

ui: fix broken get suggestions on search

---

cds/config.py
cds/modules/records/static/templates/cds_records/video/downloads.html
cds/modules/stats/views.py
cds/modules/theme/static/js/cds/module.js
cds/modules/theme/static/js/main.js

Other:
- ui: close checksum popover on click otside
- ui: open CERN's Terms of Use in another tab
- ui: add spacing between size and video quality
- ui: fix video wrong qualities mapping
Closes #1573

Add config for elastic search host and port and fix some UI issues

---

cds/config.py
cds/modules/records/providers.py
cds/modules/records/tasks.py

* Make the value of the user-agent that is
passed to cds configurable.

records: make user-agent configurable

---

cds/config.py
cds/modules/deposit/mappings/deposits/records/videos/project/project-v1.0.0.json
cds/modules/deposit/mappings/deposits/records/videos/video/video-v1.0.0.json
cds/modules/records/mappings/records/videos/project/project-v1.0.0.json
cds/modules/records/mappings/records/videos/video/video-v1.0.0.json
cds/modules/search_ui/static/templates/cds_search_ui/selectbox.html
cds/modules/search_ui/templates/cds_search_ui/search.html
cds/modules/theme/static/scss/cds.scss
tests/unit/test_project_rest.py

records: add a selectbox to sort the search results
deposit: change the sorting field from `_updated` to `_created`
Closes #1592 #1478

ui:  add sort options to the search interface

---

cds/config.py
cds/modules/records/search.py

* implemented lowercase filter for terms of given field
* workaround for es ver. 2 problem with uppercase strings
* (closes #1437)

global: filter lowercase for es keywords

---

cds/modules/deposit/static/js/cds_deposit/avc/components/cdsForm.js

* Point to the cds endpoint that autocompletes also
e-groups

autocomplete: change cds endpoint for autocompletion

---

cds/modules/previewer/extensions/video.py
cds/modules/previewer/templates/cds_previewer/macros/player.html
cds/modules/previewer/templates/cds_previewer/video/embed.html
cds/modules/previewer/views.py
cds/modules/redirector/views.py

* new options are configurable by adding url parameters to the requested embed
video
* added autoplay
* added turning off subtitles option
* added startTime and endTime for player
* added option of hiding the controls of the player
* added mute option
* (closes #1684)

Configurable player for embed videos

---

cds/modules/theme/static/scss/cds.scss

ui: fix search suggestions position

---

cds/config.py
cds/modules/records/tasks.py
tests/unit/test_celery.py

celery: task for checking subformats integrity

---

cds/modules/deposit/api.py
cds/modules/deposit/receivers.py
cds/modules/deposit/tasks.py
cds/modules/migrator/records.py
cds/modules/records/minters.py

Calling the DOI minter every time you edit a record

doi: fix doi minting when editing a record

---

cds/modules/fixtures/data/pages/faq.html
cds/modules/previewer/static/css/cds_previewer/video.css
cds/modules/previewer/templates/cds_previewer/macros/player.html
cds/modules/records/static/templates/cds_records/video/share.html
cds/modules/theme/static/scss/cds.scss

* adds the parameter to config player for responsive usage (backgrounds)
* adds the fix for Internet Explorer not supported object-fit
* (closes #1702)

previewer: responsive player embed video option

---

cds/modules/previewer/templates/cds_previewer/macros/player.html

* fixed API option fluid for embed responsive player
previewer: fixed typo in class name

previewer: player option fluid turned off

---

cds/modules/records/tasks.py

records: update celery tasks

---

cds/config.py
cds/modules/deposit/static/js/cds_deposit/avc/filters/progressClass.js
cds/modules/deposit/static/js/cds_deposit/avc/filters/progressIcon.js
cds/modules/deposit/static/templates/cds_deposit/search/results.html
cds/modules/deposit/tasks.py
tests/unit/test_celery.py

Angular JS trackBy $index uses the index in array to decide if should remove the underlying DOM element or not. This was causing a problem because if new data where fetched because of a facet action and the order of the results was different the records were ending up in an inconsistent state and the some projects were showing the spinner icon. More on that here https://docs.angularjs.org/api/ng/directive/ngRepeat .
Also we identified another issue that is described here https://github.com/CERNDocumentServer/cds-videos/issues/1754

deposit: fix wrong deposit statuses

---

cds/config.py
tests/unit/test_celery.py

File integration checks tasks off

---

MANIFEST.in
tests/functional/robotframework/resourceCDS.robot
tests/functional/robotframework/valid_depositQA.robot
tests/functional/robotframework/valid_depositVideos.robot
tests/functional/robotframework/valid_loginCDS.robot
tests/functional/robotframework/valid_searchQA.robot
tests/functional/robotframework/valid_searchVideos.robot

* several scripts to automate basic functional tests with RobotFramework for login, search, deposit
The scripts work with http://robotframework.org/ (over selenium webdriver, more details in the resourceCDS.robot file), which is not installed today. So the scripts cannot run, but it was agreed to centralize them in view of running on automatic trigger (CI), hence this is the first step (or the last one, if it is deemed not worth installing RobotFramework in view of what is decided for Books).

tests: scripts to automate functional tests

---

cds/modules/fixtures/data/categories.json

* Adds the IPPOG category to categories.json

Fixtures: Additional category for IPPOG

---

cds/config.py
cds/modules/home/templates/cds_home/home.html
cds/modules/theme/static/scss/cds.scss

home: add popular topics to home page

---

cds/config.py
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsDeposits.js
cds/modules/deposit/static/js/cds_deposit/avc/components/cdsUploader.js
cds/modules/deposit/static/templates/cds_deposit/deposits.html
cds/modules/deposit/static/templates/cds_deposit/types/project/form.html
cds/modules/deposit/templates/cds_deposit/edit.html
cds/modules/theme/static/scss/cds.scss

* decrease the size of the homepage video player
* prevent browser tab close while uploading videos
* better explanations on upload page of supported videos

ui: prevent tab close on upload and resize home player

---

cds/modules/deposit/api.py
cds/modules/deposit/form.py
cds/modules/deposit/static/templates/cds_deposit/deposits.html
cds/modules/deposit/static/templates/cds_deposit/search/results.html
cds/modules/deposit/static/templates/cds_deposit/types/video/actions.html
cds/modules/deposit/static/templates/cds_deposit/types/video/form.html
cds/modules/deposit/templates/cds_deposit/assign_report_number.html
cds/modules/deposit/templates/cds_deposit/index.html
cds/modules/deposit/templates/cds_deposit/reserve_report_number.html
cds/modules/deposit/views.py
cds/modules/records/providers.py
scripts/server
scripts/setup

Reseve report number

---

cds/config.py
cds/modules/deposit/fetcher.py
cds/modules/records/forms.py
cds/modules/records/templates/cds_records/record_delete.html
cds/modules/records/templates/cds_records/records_delete_report.html
cds/modules/records/utils.py
cds/modules/records/views.py

Admin form to delete videos 

---

CHANGES.rst
cds/config.py
cds/modules/records/providers.py
cds/modules/records/static/js/cds_records/user_actions_logger.js
cds/version.py
tests/unit/conftest.py
tests/unit/helpers.py
tests/unit/test_project.py
tests/unit/test_records.py
tests/unit/test_video.py
tests/unit/test_video_rest.py

Co-authored-by: Zacharias Zacharodimos <zacharias.zacharodimos@cern.ch>

records: decouple rec id provider

---

requirements.packages.txt

* See https://github.com/lxml/lxml/security/advisories/GHSA-55x5-fj6c-h6m8

deps: update lxml due to security issue

---

cds/modules/deposit/static/templates/cds_deposit/types/video/action_delete.html
cds/modules/deposit/static/templates/cds_deposit/types/video/actions.html
cds/modules/flows/tasks.py

Disables delele button until extract frames task is done

flows: handle pid deletion exception on tasks

---

CHANGES.rst
cds/modules/fixtures/data/categories.json
cds/modules/theme/bundles.py
cds/version.py
requirements.packages.txt

categories: add ALICE

---

cds/modules/opencast/tasks.py
cds/modules/previewer/extensions/video.py
cds/modules/previewer/templates/cds_previewer/base.html

* Changes title of preview tab to title
of the video

opencast: fix celery task abrupt stop

---

cds/config.py
cds/modules/oauthclient/__init__.py
cds/modules/oauthclient/cern_openid.py
cds/modules/theme/templates/cds_theme/header.html
requirements.packages.txt
setup.py

https://gitlab.cern.ch/cds-team/cds-videos-openshift/-/issues/1

integrate new SSO

---

docker-services.yml

- Changed Postgres version from 12.5 to 14 just to see f it works right away.

Development: testing new DB version

---

cds/modules/deposit/static/templates/cds_deposit/list.html
cds/modules/deposit/static/templates/cds_deposit/types/video/uploader.html
cds/modules/records/static/templates/cds_records/video/downloads.html
cds/modules/theme/static/js/cds/module.js
cds/modules/theme/static/scss/cds.scss

- Overriding user agent style to fix popover API update on Chrome
- Conditional on file size to decide whether or not to display warning

Development: download button and download header fix

---

cds/modules/records/static/templates/cds_records/video/downloads.html

- Adjusted value for file size warning. It was 1Gb and now it's 100Mb.

Development: file size warning adjusted to 100Mb

---

cds/modules/deposit/static/templates/cds_deposit/types/video/uploader.html

upload: add suggestion on how to upload a cover for a video

---

cds/modules/fixtures/data/pages/faq.html

Used existing cds-anchor class for all `<a>` tags.

Added anchor tags to all questions in static FAQ.

---

cds/modules/invenio_deposit/views/ui.py
cds/modules/theme/assets/bootstrap3/js/cds_deposit/avc/components/cdsDeposit.js

1. Currently when you press edit project, the ckeditor description field still remains disabled.
2. If you press publish on video, it disables the main project ckeditor description field too.
This PR fixes both.

cds_deposit: Use apply on ckeditor readonly for immediate update

---

cds/modules/oauthclient/cern_openid.py

* fetch extra roles, cached in the DB, when the user login using a personal access token.
* related: https://github.com/inveniosoftware/invenio-oauthclient/issues/291

contrib: fix CERN contrib login with token

---

cds/config.py
cds/modules/home/templates/cds_home/home.html
cds/modules/theme/assets/bootstrap3/js/cds/app.js
cds/modules/theme/assets/bootstrap3/scss/cds/cds.scss
cds/modules/theme/static/templates/cds/video/small_video_card.html

homepage: display lectures

---

cds/modules/deposit/static/templates/cds_deposit/types/video/uploader.html
cds/modules/previewer/templates/cds_previewer/macros/player.html
cds/modules/records/static/templates/cds_records/video/detail.html
cds/modules/theme/assets/bootstrap3/js/cds_deposit/avc/components/cdsUploader.js
cds/modules/theme/assets/bootstrap3/js/cds_records/cdsRecord.js
cds/modules/theme/assets/bootstrap3/scss/cds/cds.scss
cds/modules/theme/webpack.py

Transcriptions can enable here:
You can search and follow transcriptions:

feature: follow and search transcriptions

---

cds/modules/deposit/api.py
cds/modules/flows/tasks.py
cds/modules/records/static/templates/cds_records/video/detail.html
cds/modules/theme/assets/bootstrap3/js/cds_records/cdsRecord.js

- If any chapter is at the end of the video (same as the duration), ffmpeg was failing.
- Landing page was getting each frame twice, instead of that we'll store them at the beginning

chapters: improve task and landing page
